'use client';
import useSWR from 'swr';
import { api } from '@/lib/api';

type Row = Record<string, unknown>;

export default function FuncionarioPage() {
  const { data, error, isLoading } = useSWR<Row[]>('/funcionarios', api);
  if (isLoading) return <p>Loading…</p>;
  if (error) return <p>Failed to load.</p>;
  return (
    <main>
      <h1>Funcionarios</h1>
      <table>
        <thead><tr><th style={{ textAlign: 'left', padding: '4px 8px' }}>id</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>nome</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>nomeGuerra</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>numeroFuncional</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>cpf</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>sexo</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>fone</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>vinculoValido</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>celular</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>email</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>estadoCivil</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>grupoSanguineo</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>racaCor</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>dataNascimento</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>cidadeNascimento</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>ufNascimento</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>paisNascimento</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>nacionalidade</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>nomePai</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>nomeMae</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>prontuarioHpm</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>tipoCadastro</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>ativo</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>documentosFuncionario</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>dadosBancariosFuncionario</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>historicoProfissional</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>vestimenta</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>tamanho</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>adido</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>corOlhos</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>corCabelos</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>sinaisParticulares</th><th style={{ textAlign: 'left', padding: '4px 8px' }}>altura</th></tr></thead>
        <tbody>
          {(data ?? []).map((row, i) => (
            <tr key={i}><td style={{ padding: '4px 8px' }}>{String(row.id ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.nome ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.nomeGuerra ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.numeroFuncional ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.cpf ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.sexo ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.fone ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.vinculoValido ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.celular ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.email ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.estadoCivil ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.grupoSanguineo ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.racaCor ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.dataNascimento ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.cidadeNascimento ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.ufNascimento ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.paisNascimento ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.nacionalidade ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.nomePai ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.nomeMae ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.prontuarioHpm ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.tipoCadastro ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.ativo ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.documentosFuncionario ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.dadosBancariosFuncionario ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.historicoProfissional ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.vestimenta ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.tamanho ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.adido ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.corOlhos ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.corCabelos ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.sinaisParticulares ?? '')}</td><td style={{ padding: '4px 8px' }}>{String(row.altura ?? '')}</td></tr>
          ))}
        </tbody>
      </table>
    </main>
  );
}
