"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { ncmenumSchema, type NcmenumInput } from "@/lib/validation/ncmenum";

// Ncmenum — create/edit form, generated by RNC from the UIR.
export default function NcmenumForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<NcmenumInput>({ resolver: zodResolver(ncmenumSchema) });

  async function onSubmit(values: NcmenumInput) {
    const res = await fetch("/api/ncmenums", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/ncmenums");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Ncmenum</h1>
      <div className="space-y-1">
        <label htmlFor="menuSelection" className="text-sm font-medium">Menu Selection *</label>
        <Input id="menuSelection" type="text" placeholder="Enter menu selection" {...register("menuSelection")} />
        {errors.menuSelection && <p className="text-sm text-red-500">{String(errors.menuSelection?.message ?? "")}</p>}
      </div>
      <Button type="submit">Save</Button>
    </form>
  );
}
