"use client";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { customerDetailsSchema, type CustomerDetailsInput } from "@/lib/validation/customerDetails";

// Customer Dashboars Yt Bank Of India — create/edit form, generated by RNC from the UIR.
export default function CustomerDetailsForm() {
  const router = useRouter();
  const { register, handleSubmit, control, formState: { errors, isSubmitting } } =
    useForm<CustomerDetailsInput>({ resolver: zodResolver(customerDetailsSchema) });

  async function onSubmit(values: CustomerDetailsInput) {
    const res = await fetch("/api/customer_details", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/customer_details");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/customer_details"><ArrowLeft className="h-4 w-4" /> Back to Customer Details</Link>
      </Button>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Card>
          <CardHeader>
            <CardTitle>Customer Dashboars Yt Bank Of India</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <label htmlFor="accountNo" className="text-sm font-medium">Account No</label>
              <Input id="accountNo" type="text" placeholder="Enter account no" {...register("accountNo")} />
              {errors.accountNo && <p className="text-sm text-destructive">{String(errors.accountNo?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="accountBallance" className="text-sm font-medium">Account Balance</label>
              <Input id="accountBallance" type="text" placeholder="Enter account balance" {...register("accountBallance")} />
              {errors.accountBallance && <p className="text-sm text-destructive">{String(errors.accountBallance?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="name" className="text-sm font-medium">Name</label>
              <Input id="name" type="text" placeholder="Enter name" {...register("name")} />
              {errors.name && <p className="text-sm text-destructive">{String(errors.name?.message ?? "")}</p>}
            </div>
          </CardContent>
          <CardFooter className="justify-end gap-2">
            <Button type="button" variant="outline" asChild>
              <Link href="/customer_details">Cancel</Link>
            </Button>
            <Button type="submit" disabled={isSubmitting}>Save</Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  );
}
