"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { customerDetailsSchema, type CustomerDetailsInput } from "@/lib/validation/customerDetails";

// Update Customer Details — create/edit form, generated by RNC from the UIR.
export default function CustomerDetailsForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<CustomerDetailsInput>({ resolver: zodResolver(customerDetailsSchema) });

  async function onSubmit(values: CustomerDetailsInput) {
    const res = await fetch("/api/customer_details", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/customer_details");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Update Customer Details</h1>
      <div className="space-y-1">
        <label htmlFor="address" className="text-sm font-medium">UpdateAddressText</label>
        <Input id="address" type="text" placeholder="Enter updateaddresstext" {...register("address")} />
        {errors.address && <p className="text-sm text-red-500">{String(errors.address?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="phoneno" className="text-sm font-medium">UpdatePhoneText</label>
        <Input id="phoneno" type="tel" placeholder="Enter updatephonetext" {...register("phoneno")} />
        {errors.phoneno && <p className="text-sm text-red-500">{String(errors.phoneno?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="email" className="text-sm font-medium">UpdateText</label>
        <Input id="email" type="email" placeholder="Enter updatetext" {...register("email")} />
        {errors.email && <p className="text-sm text-red-500">{String(errors.email?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="image" className="text-sm font-medium">showimglink</label>
        <Input id="image" type="text" placeholder="Enter showimglink" {...register("image")} />
        {errors.image && <p className="text-sm text-red-500">{String(errors.image?.message ?? "")}</p>}
      </div>
      <Button type="submit">Save</Button>
    </form>
  );
}
