"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { ComboboxCreate } from "@/components/ui/combobox-create";
import { customerSchema, type CustomerInput } from "@/lib/validation/customer";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Lookup field → options fetched live from the referenced entity's API.
function RelationSelect({ route, optionLabel, value, onChange }: {
  route: string; optionLabel: string; value: string; onChange: (v: string) => void;
}) {
  const { data } = useSWR(`/api/${route}?page=1&limit=100`, fetcher);
  const rows: any[] = data?.data ?? [];
  return (
    <Select value={value ?? ""} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Select…" /></SelectTrigger>
      <SelectContent>
        {rows.map((row) => (
          <SelectItem key={row.id} value={String(row.id)}>{String(row[optionLabel] ?? row.id)}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// Ed Cust — edit view, generated by RNC from the UIR.
export default function CustomerEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/customers/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<CustomerInput>({ resolver: zodResolver(customerSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: CustomerInput) {
    const res = await fetch(`/api/customers/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/customers");
  }

  async function onDelete() {
    const res = await fetch(`/api/customers/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/customers");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/customers"><ArrowLeft className="h-4 w-4" /> Back to Customers</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Ed Cust</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="zip" className="text-sm font-medium">Zip Code</label>
                <Input id="zip" type="text" placeholder="Enter zip code" {...register("zip")} />
                {errors.zip && <p className="text-sm text-destructive">{String(errors.zip?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="company" className="text-sm font-medium">Company</label>
                <Input id="company" type="text" placeholder="Enter company" {...register("company")} />
                {errors.company && <p className="text-sm text-destructive">{String(errors.company?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="addr1" className="text-sm font-medium">Address 1</label>
                <Input id="addr1" type="text" placeholder="Enter address 1" {...register("addr1")} />
                {errors.addr1 && <p className="text-sm text-destructive">{String(errors.addr1?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="addr2" className="text-sm font-medium">Address 2</label>
                <Input id="addr2" type="text" placeholder="Enter address 2" {...register("addr2")} />
                {errors.addr2 && <p className="text-sm text-destructive">{String(errors.addr2?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="city" className="text-sm font-medium">City</label>
                <Input id="city" type="text" placeholder="Enter city" {...register("city")} />
                {errors.city && <p className="text-sm text-destructive">{String(errors.city?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="state" className="text-sm font-medium">State</label>
                <Input id="state" type="text" placeholder="Enter state" {...register("state")} />
                {errors.state && <p className="text-sm text-destructive">{String(errors.state?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="country" className="text-sm font-medium">Country</label>
                <Input id="country" type="text" placeholder="Enter country" {...register("country")} />
                {errors.country && <p className="text-sm text-destructive">{String(errors.country?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="phone" className="text-sm font-medium">Phone</label>
                <Input id="phone" type="tel" placeholder="Enter phone" {...register("phone")} />
                {errors.phone && <p className="text-sm text-destructive">{String(errors.phone?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="taxRate" className="text-sm font-medium">Tax Rate</label>
                <Input id="taxRate" type="text" placeholder="Enter tax rate" {...register("taxRate")} />
                {errors.taxRate && <p className="text-sm text-destructive">{String(errors.taxRate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="contact" className="text-sm font-medium">Contact</label>
                <Input id="contact" type="text" placeholder="Enter contact" {...register("contact")} />
                {errors.contact && <p className="text-sm text-destructive">{String(errors.contact?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="lastInvoiceDate" className="text-sm font-medium">Last Invoice Date</label>
                <Input id="lastInvoiceDate" type="text" placeholder="Enter last invoice date" {...register("lastInvoiceDate")} />
                {errors.lastInvoiceDate && <p className="text-sm text-destructive">{String(errors.lastInvoiceDate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="fax" className="text-sm font-medium">Fax</label>
                <Input id="fax" type="text" placeholder="Enter fax" {...register("fax")} />
                {errors.fax && <p className="text-sm text-destructive">{String(errors.fax?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
