"use client";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { searchDlgSchema, type SearchDlgInput } from "@/lib/validation/searchDlg";

// Search Dlg — create/edit form, generated by RNC from the UIR.
export default function SearchDlgForm() {
  const router = useRouter();
  const { register, handleSubmit, control, formState: { errors, isSubmitting } } =
    useForm<SearchDlgInput>({ resolver: zodResolver(searchDlgSchema) });

  async function onSubmit(values: SearchDlgInput) {
    const res = await fetch("/api/search_dlgs", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/search_dlgs");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/search_dlgs"><ArrowLeft className="h-4 w-4" /> Back to Search Dlgs</Link>
      </Button>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Card>
          <CardHeader>
            <CardTitle>Search Dlg</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <label htmlFor="field1" className="text-sm font-medium">Field 1</label>
              <Input id="field1" type="text" placeholder="Enter field 1" {...register("field1")} />
              {errors.field1 && <p className="text-sm text-destructive">{String(errors.field1?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="field2" className="text-sm font-medium">Field 2</label>
              <Controller
                control={control}
                name={"field2" as never}
                render={({ field }) => (
                  <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                    <SelectTrigger id="field2"><SelectValue placeholder="Select…" /></SelectTrigger>
                    <SelectContent>
                    </SelectContent>
                  </Select>
                )}
              />
              {errors.field2 && <p className="text-sm text-destructive">{String(errors.field2?.message ?? "")}</p>}
            </div>
          </CardContent>
          <CardFooter className="justify-end gap-2">
            <Button type="button" variant="outline" asChild>
              <Link href="/search_dlgs">Cancel</Link>
            </Button>
            <Button type="submit" disabled={isSubmitting}>Save</Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  );
}
