"use client";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { ComboboxCreate } from "@/components/ui/combobox-create";
import { itemsSchema, type ItemsInput } from "@/lib/validation/items";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Lookup field → options fetched live from the referenced entity's API.
function RelationSelect({ route, optionLabel, value, onChange }: {
  route: string; optionLabel: string; value: string; onChange: (v: string) => void;
}) {
  const { data } = useSWR(`/api/${route}?page=1&limit=100`, fetcher);
  const rows: any[] = data?.data ?? [];
  return (
    <Select value={value ?? ""} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Select…" /></SelectTrigger>
      <SelectContent>
        {rows.map((row) => (
          <SelectItem key={row.id} value={String(row.id)}>{String(row[optionLabel] ?? row.id)}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// Items — create/edit form, generated by RNC from the UIR.
export default function ItemsForm() {
  const router = useRouter();
  const { register, handleSubmit, control, formState: { errors, isSubmitting } } =
    useForm<ItemsInput>({ resolver: zodResolver(itemsSchema) });

  async function onSubmit(values: ItemsInput) {
    const res = await fetch("/api/items", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/items");
  }

  return (
    <div className="w-full px-6 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/items"><ArrowLeft className="h-4 w-4" /> Back to Items</Link>
      </Button>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Card>
          <CardHeader>
            <CardTitle>Items</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <label htmlFor="description" className="text-sm font-medium">Description</label>
              <Input id="description" type="text" placeholder="Enter description" {...register("description")} />
              {errors.description && <p className="text-sm text-destructive">{String(errors.description?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="itemno" className="text-sm font-medium">Itemno</label>
              <Input id="itemno" type="text" placeholder="Enter itemno" {...register("itemno")} />
              {errors.itemno && <p className="text-sm text-destructive">{String(errors.itemno?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="orderno" className="text-sm font-medium">Orderno</label>
              <Input id="orderno" type="text" placeholder="Enter orderno" {...register("orderno")} />
              {errors.orderno && <p className="text-sm text-destructive">{String(errors.orderno?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="sellprice" className="text-sm font-medium">Sellprice</label>
              <Input id="sellprice" type="text" placeholder="Enter sellprice" {...register("sellprice")} />
              {errors.sellprice && <p className="text-sm text-destructive">{String(errors.sellprice?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="qty" className="text-sm font-medium">Qty</label>
              <Input id="qty" type="text" placeholder="Enter qty" {...register("qty")} />
              {errors.qty && <p className="text-sm text-destructive">{String(errors.qty?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="discount" className="text-sm font-medium">Discount</label>
              <Input id="discount" type="text" placeholder="Enter discount" {...register("discount")} />
              {errors.discount && <p className="text-sm text-destructive">{String(errors.discount?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="extprice" className="text-sm font-medium">Extprice</label>
              <Input id="extprice" type="text" placeholder="Enter extprice" {...register("extprice")} />
              {errors.extprice && <p className="text-sm text-destructive">{String(errors.extprice?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="partno" className="text-sm font-medium">Partno</label>
              <Input id="partno" type="text" placeholder="Enter partno" {...register("partno")} />
              {errors.partno && <p className="text-sm text-destructive">{String(errors.partno?.message ?? "")}</p>}
            </div>
          </CardContent>
          <CardFooter className="justify-end gap-2">
            <Button type="button" variant="outline" asChild>
              <Link href="/items">Cancel</Link>
            </Button>
            <Button type="submit" disabled={isSubmitting}>Save</Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  );
}
