"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { withdrawSchema, type WithdrawInput } from "@/lib/validation/withdraw";

// Withdraw Balance Yt Bank Of India — create/edit form, generated by RNC from the UIR.
export default function WithdrawForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<WithdrawInput>({ resolver: zodResolver(withdrawSchema) });

  async function onSubmit(values: WithdrawInput) {
    const res = await fetch("/api/withdraws", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/withdraws");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Withdraw Balance Yt Bank Of India</h1>
      <div className="space-y-1">
        <label htmlFor="accountBallance" className="text-sm font-medium">balancebeforewithdraw</label>
        <Input id="accountBallance" type="text" placeholder="Enter balancebeforewithdraw" {...register("accountBallance")} />
        {errors.accountBallance && <p className="text-sm text-red-500">{String(errors.accountBallance?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="withdrawBalance" className="text-sm font-medium">withdrawballance</label>
        <Input id="withdrawBalance" type="text" placeholder="Enter withdrawballance" {...register("withdrawBalance")} />
        {errors.withdrawBalance && <p className="text-sm text-red-500">{String(errors.withdrawBalance?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="newTotalBalance" className="text-sm font-medium">newtotalballance</label>
        <Input id="newTotalBalance" type="text" placeholder="Enter newtotalballance" {...register("newTotalBalance")} />
        {errors.newTotalBalance && <p className="text-sm text-red-500">{String(errors.newTotalBalance?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="balanceBeforeWithdraw" className="text-sm font-medium">fillbalancebeforewithdraw</label>
        <Input id="balanceBeforeWithdraw" type="text" placeholder="Enter fillbalancebeforewithdraw" {...register("balanceBeforeWithdraw")} />
        {errors.balanceBeforeWithdraw && <p className="text-sm text-red-500">{String(errors.balanceBeforeWithdraw?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountBallance" className="text-sm font-medium">TotalBalancecustomer</label>
        <Input id="accountBallance" type="text" placeholder="Enter totalbalancecustomer" {...register("accountBallance")} />
        {errors.accountBallance && <p className="text-sm text-red-500">{String(errors.accountBallance?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="transactionId" className="text-sm font-medium">transactionid</label>
        <Input id="transactionId" type="text" placeholder="Enter transactionid" {...register("transactionId")} />
        {errors.transactionId && <p className="text-sm text-red-500">{String(errors.transactionId?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="macId" className="text-sm font-medium">macid</label>
        <Input id="macId" type="text" placeholder="Enter macid" {...register("macId")} />
        {errors.macId && <p className="text-sm text-red-500">{String(errors.macId?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountNo" className="text-sm font-medium">accountno</label>
        <Input id="accountNo" type="text" placeholder="Enter accountno" {...register("accountNo")} />
        {errors.accountNo && <p className="text-sm text-red-500">{String(errors.accountNo?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountNo" className="text-sm font-medium">newaccountno</label>
        <Input id="accountNo" type="text" placeholder="Enter newaccountno" {...register("accountNo")} />
        {errors.accountNo && <p className="text-sm text-red-500">{String(errors.accountNo?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="withdrawTime" className="text-sm font-medium">LabelTime</label>
        <Input id="withdrawTime" type="text" placeholder="Enter labeltime" {...register("withdrawTime")} />
        {errors.withdrawTime && <p className="text-sm text-red-500">{String(errors.withdrawTime?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="withdrawDate" className="text-sm font-medium">datecap</label>
        <Input id="withdrawDate" type="text" placeholder="Enter datecap" {...register("withdrawDate")} />
        {errors.withdrawDate && <p className="text-sm text-red-500">{String(errors.withdrawDate?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountNo" className="text-sm font-medium">Label1</label>
        <Input id="accountNo" type="text" placeholder="Enter label1" {...register("accountNo")} />
        {errors.accountNo && <p className="text-sm text-red-500">{String(errors.accountNo?.message ?? "")}</p>}
      </div>
      <Button type="submit">Save</Button>
    </form>
  );
}
