"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { contactUsYtBankOfIndiaSchema, type ContactUsYtBankOfIndiaInput } from "@/lib/validation/contactUsYtBankOfIndia";

// Contact Us Yt Bank Of India — create/edit form, generated by RNC from the UIR.
export default function ContactUsYtBankOfIndiaForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<ContactUsYtBankOfIndiaInput>({ resolver: zodResolver(contactUsYtBankOfIndiaSchema) });

  async function onSubmit(values: ContactUsYtBankOfIndiaInput) {
    const res = await fetch("/api/contact_us_yt_bank_of_indias", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/contact_us_yt_bank_of_indias");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Contact Us Yt Bank Of India</h1>
      <Button type="submit">Save</Button>
    </form>
  );
}
