"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { nccruiseSchema, type NccruiseInput } from "@/lib/validation/nccruise";

// Ncdemapm — create/edit form, generated by RNC from the UIR.
export default function NccruiseForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<NccruiseInput>({ resolver: zodResolver(nccruiseSchema) });

  async function onSubmit(values: NccruiseInput) {
    const res = await fetch("/api/nccruises", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/nccruises");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Ncdemapm</h1>
      <div className="space-y-1">
        <label htmlFor="cruiseId" className="text-sm font-medium">Cruise ID</label>
        <Input id="cruiseId" type="number" placeholder="Enter cruise id" {...register("cruiseId")} />
        {errors.cruiseId && <p className="text-sm text-red-500">{String(errors.cruiseId?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="yachtName" className="text-sm font-medium">Yacht Name</label>
        <Input id="yachtName" type="text" placeholder="Enter yacht name" {...register("yachtName")} />
        {errors.yachtName && <p className="text-sm text-red-500">{String(errors.yachtName?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="startHarbor" className="text-sm font-medium">Start Harbor</label>
        <Input id="startHarbor" type="text" placeholder="Enter start harbor" {...register("startHarbor")} />
        {errors.startHarbor && <p className="text-sm text-red-500">{String(errors.startHarbor?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="destinationHarbor" className="text-sm font-medium">Destination Harbor</label>
        <Input id="destinationHarbor" type="text" placeholder="Enter destination harbor" {...register("destinationHarbor")} />
        {errors.destinationHarbor && <p className="text-sm text-red-500">{String(errors.destinationHarbor?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="startDate" className="text-sm font-medium">Start Date</label>
        <Input id="startDate" type="number" placeholder="Enter start date" {...register("startDate")} />
        {errors.startDate && <p className="text-sm text-red-500">{String(errors.startDate?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="startTime" className="text-sm font-medium">Start Time</label>
        <Input id="startTime" type="number" placeholder="Enter start time" {...register("startTime")} />
        {errors.startTime && <p className="text-sm text-red-500">{String(errors.startTime?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="endDate" className="text-sm font-medium">End Date</label>
        <Input id="endDate" type="number" placeholder="Enter end date" {...register("endDate")} />
        {errors.endDate && <p className="text-sm text-red-500">{String(errors.endDate?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="endTime" className="text-sm font-medium">End Time</label>
        <Input id="endTime" type="number" placeholder="Enter end time" {...register("endTime")} />
        {errors.endTime && <p className="text-sm text-red-500">{String(errors.endTime?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="cruiseStatus" className="text-sm font-medium">Cruise Status</label>
        <select id="cruiseStatus" className="h-9 w-full rounded-md border px-3" {...register("cruiseStatus")}>
          <option value="">—</option>
          <option value="0">0</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
        </select>
        {errors.cruiseStatus && <p className="text-sm text-red-500">{String(errors.cruiseStatus?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="price1W" className="text-sm font-medium">Price 1 Week</label>
        <Input id="price1W" type="number" placeholder="Enter price 1 week" {...register("price1W")} />
        {errors.price1W && <p className="text-sm text-red-500">{String(errors.price1W?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="price2W" className="text-sm font-medium">Price 2 Weeks</label>
        <Input id="price2W" type="number" placeholder="Enter price 2 weeks" {...register("price2W")} />
        {errors.price2W && <p className="text-sm text-red-500">{String(errors.price2W?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="price3W" className="text-sm font-medium">Price 3 Weeks</label>
        <Input id="price3W" type="number" placeholder="Enter price 3 weeks" {...register("price3W")} />
        {errors.price3W && <p className="text-sm text-red-500">{String(errors.price3W?.message ?? "")}</p>}
      </div>
      <Button type="submit">Save</Button>
    </form>
  );
}
