"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { deositeTransactionHistorySchema, type DeositeTransactionHistoryInput } from "@/lib/validation/deositeTransactionHistory";

// Deosite Transaction History — create/edit form, generated by RNC from the UIR.
export default function DeositeTransactionHistoryForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<DeositeTransactionHistoryInput>({ resolver: zodResolver(deositeTransactionHistorySchema) });

  async function onSubmit(values: DeositeTransactionHistoryInput) {
    const res = await fetch("/api/deosite_transaction_histories", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/deosite_transaction_histories");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Deosite Transaction History</h1>
      <Button type="submit">Save</Button>
    </form>
  );
}
