"use client";
import useSWR from "swr";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Nccruises — list view, generated by RNC from the UIR.
export default function NccruisesPage() {
  const { data, isLoading } = useSWR(`/api/nccruises?page=1&limit=20`, fetcher);
  const rows = data?.data ?? [];

  return (
    <div className="container mx-auto py-8">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold">Nccruises</h1>
        <Button asChild><Link href="/nccruises/new">New Ncdemapm</Link></Button>
      </div>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b text-left">
            <th className="py-2 pr-4">Cruise ID</th>
            <th className="py-2 pr-4">Yacht Name</th>
            <th className="py-2 pr-4">Start Harbor</th>
            <th className="py-2 pr-4">Destination Harbor</th>
            <th className="py-2 pr-4">Start Date</th>
            <th className="py-2 pr-4">Start Time</th>
            <th className="py-2 pr-4">End Date</th>
            <th className="py-2 pr-4">End Time</th>
            <th className="py-2 pr-4">Cruise Status</th>
            <th className="py-2 pr-4">Price 1 Week</th>
            <th className="py-2 pr-4">Price 2 Weeks</th>
            <th className="py-2 pr-4">Price 3 Weeks</th>
            <th className="py-2"></th>
          </tr>
        </thead>
        <tbody>
          {isLoading && (<tr><td className="py-4 text-muted-foreground">Loading…</td></tr>)}
          {rows.map((row: any) => (
            <tr key={row.id} className="border-b">
              <td className="py-2 pr-4">{String(row.cruiseId ?? "")}</td>
              <td className="py-2 pr-4">{String(row.yachtName ?? "")}</td>
              <td className="py-2 pr-4">{String(row.startHarbor ?? "")}</td>
              <td className="py-2 pr-4">{String(row.destinationHarbor ?? "")}</td>
              <td className="py-2 pr-4">{String(row.startDate ?? "")}</td>
              <td className="py-2 pr-4">{String(row.startTime ?? "")}</td>
              <td className="py-2 pr-4">{String(row.endDate ?? "")}</td>
              <td className="py-2 pr-4">{String(row.endTime ?? "")}</td>
              <td className="py-2 pr-4">{String(row.cruiseStatus ?? "")}</td>
              <td className="py-2 pr-4">{String(row.price1W ?? "")}</td>
              <td className="py-2 pr-4">{String(row.price2W ?? "")}</td>
              <td className="py-2 pr-4">{String(row.price3W ?? "")}</td>
              <td className="py-2">
                <Button variant="ghost" size="sm" asChild>
                  <Link href={`/nccruises/${row.id}/edit`}>Edit</Link>
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
