"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { nccruiseSchema, type NccruiseInput } from "@/lib/validation/nccruise";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Lookup field → options fetched live from the referenced entity's API.
function RelationSelect({ route, optionLabel, value, onChange }: {
  route: string; optionLabel: string; value: string; onChange: (v: string) => void;
}) {
  const { data } = useSWR(`/api/${route}?page=1&limit=100`, fetcher);
  const rows: any[] = data?.data ?? [];
  return (
    <Select value={value ?? ""} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Select…" /></SelectTrigger>
      <SelectContent>
        {rows.map((row) => (
          <SelectItem key={row.id} value={String(row.id)}>{String(row[optionLabel] ?? row.id)}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// Ncdemapm — edit view, generated by RNC from the UIR.
export default function NccruiseEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/nccruises/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<NccruiseInput>({ resolver: zodResolver(nccruiseSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: NccruiseInput) {
    const res = await fetch(`/api/nccruises/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/nccruises");
  }

  async function onDelete() {
    const res = await fetch(`/api/nccruises/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/nccruises");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/nccruises"><ArrowLeft className="h-4 w-4" /> Back to Nccruises</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Ncdemapm</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="yachtName" className="text-sm font-medium">Yacht Name</label>
                <Input id="yachtName" type="text" placeholder="Enter yacht name" {...register("yachtName")} />
                {errors.yachtName && <p className="text-sm text-destructive">{String(errors.yachtName?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="cruiseId" className="text-sm font-medium">Cruise Id</label>
                <Input id="cruiseId" type="number" placeholder="Enter cruise id" {...register("cruiseId")} />
                {errors.cruiseId && <p className="text-sm text-destructive">{String(errors.cruiseId?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="startHarbor" className="text-sm font-medium">Start Harbor</label>
                <Input id="startHarbor" type="text" placeholder="Enter start harbor" {...register("startHarbor")} />
                {errors.startHarbor && <p className="text-sm text-destructive">{String(errors.startHarbor?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="destinationHarbor" className="text-sm font-medium">Destination Harbor</label>
                <Input id="destinationHarbor" type="text" placeholder="Enter destination harbor" {...register("destinationHarbor")} />
                {errors.destinationHarbor && <p className="text-sm text-destructive">{String(errors.destinationHarbor?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="startDate" className="text-sm font-medium">Start Date</label>
                <Input id="startDate" type="number" placeholder="Enter start date" {...register("startDate")} />
                {errors.startDate && <p className="text-sm text-destructive">{String(errors.startDate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="startTime" className="text-sm font-medium">Start Time</label>
                <Input id="startTime" type="number" placeholder="Enter start time" {...register("startTime")} />
                {errors.startTime && <p className="text-sm text-destructive">{String(errors.startTime?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="endDate" className="text-sm font-medium">End Date</label>
                <Input id="endDate" type="number" placeholder="Enter end date" {...register("endDate")} />
                {errors.endDate && <p className="text-sm text-destructive">{String(errors.endDate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="endTime" className="text-sm font-medium">End Time</label>
                <Input id="endTime" type="number" placeholder="Enter end time" {...register("endTime")} />
                {errors.endTime && <p className="text-sm text-destructive">{String(errors.endTime?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="cruiseStatus" className="text-sm font-medium">Cruise Status</label>
                <Controller
                  control={control}
                  name={"cruiseStatus" as never}
                  render={({ field }) => (
                    <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                      <SelectTrigger id="cruiseStatus"><SelectValue placeholder="Select…" /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="0">0</SelectItem>
                        <SelectItem value="1">1</SelectItem>
                        <SelectItem value="2">2</SelectItem>
                        <SelectItem value="3">3</SelectItem>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.cruiseStatus && <p className="text-sm text-destructive">{String(errors.cruiseStatus?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="price1W" className="text-sm font-medium">Price 1W</label>
                <Input id="price1W" type="number" placeholder="Enter price 1w" {...register("price1W")} />
                {errors.price1W && <p className="text-sm text-destructive">{String(errors.price1W?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="price2W" className="text-sm font-medium">Price 2W</label>
                <Input id="price2W" type="number" placeholder="Enter price 2w" {...register("price2W")} />
                {errors.price2W && <p className="text-sm text-destructive">{String(errors.price2W?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="price3W" className="text-sm font-medium">Price 3W</label>
                <Input id="price3W" type="number" placeholder="Enter price 3w" {...register("price3W")} />
                {errors.price3W && <p className="text-sm text-destructive">{String(errors.price3W?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
