"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { customerLoginAreaSchema, type CustomerLoginAreaInput } from "@/lib/validation/customerLoginArea";

// Customer Login Area — create/edit form, generated by RNC from the UIR.
export default function CustomerLoginAreaForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<CustomerLoginAreaInput>({ resolver: zodResolver(customerLoginAreaSchema) });

  async function onSubmit(values: CustomerLoginAreaInput) {
    const res = await fetch("/api/customer_login_areas", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/customer_login_areas");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Customer Login Area</h1>
      <Button type="submit">Save</Button>
    </form>
  );
}
