"use client";
import useSWR from "swr";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// New Customer Registrations — list view, generated by RNC from the UIR.
export default function NewCustomerRegistrationsPage() {
  const { data, isLoading } = useSWR(`/api/new_customer_registrations?page=1&limit=20`, fetcher);
  const rows = data?.data ?? [];

  return (
    <div className="container mx-auto py-8">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold">New Customer Registrations</h1>
        <Button asChild><Link href="/new_customer_registrations/new">New Register Now Customer</Link></Button>
      </div>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b text-left">
            <th className="py-2 pr-4">dob</th>
            <th className="py-2 pr-4">pwText</th>
            <th className="py-2 pr-4">addressText</th>
            <th className="py-2 pr-4">gvtidCombo</th>
            <th className="py-2 pr-4">phoneText</th>
            <th className="py-2 pr-4">genderCombo</th>
            <th className="py-2 pr-4">emailText</th>
            <th className="py-2 pr-4">AccuuntCombo</th>
            <th className="py-2 pr-4">govtidnoText</th>
            <th className="py-2 pr-4">nameText</th>
            <th className="py-2 pr-4">usernameText</th>
            <th className="py-2 pr-4">showimglink</th>
            <th className="py-2 pr-4">datelabel</th>
            <th className="py-2"></th>
          </tr>
        </thead>
        <tbody>
          {isLoading && (<tr><td className="py-4 text-muted-foreground">Loading…</td></tr>)}
          {rows.map((row: any) => (
            <tr key={row.id} className="border-b">
              <td className="py-2 pr-4">{String(row.dob ?? "")}</td>
              <td className="py-2 pr-4">{String(row.password ?? "")}</td>
              <td className="py-2 pr-4">{String(row.address ?? "")}</td>
              <td className="py-2 pr-4">{String(row.gvtidType ?? "")}</td>
              <td className="py-2 pr-4">{String(row.phoneno ?? "")}</td>
              <td className="py-2 pr-4">{String(row.gender ?? "")}</td>
              <td className="py-2 pr-4">{String(row.email ?? "")}</td>
              <td className="py-2 pr-4">{String(row.accountType ?? "")}</td>
              <td className="py-2 pr-4">{String(row.gvtidNo ?? "")}</td>
              <td className="py-2 pr-4">{String(row.name ?? "")}</td>
              <td className="py-2 pr-4">{String(row.usernamee ?? "")}</td>
              <td className="py-2 pr-4">{String(row.image ?? "")}</td>
              <td className="py-2 pr-4">{String(row.regDate ?? "")}</td>
              <td className="py-2">
                <Button variant="ghost" size="sm" asChild>
                  <Link href={`/new_customer_registrations/${row.id}/edit`}>Edit</Link>
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
