"use client";
import { useState } from "react";
import useSWR from "swr";
import Link from "next/link";
import { Plus, Search, Pencil, Inbox } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";

const fetcher = (url: string) => fetch(url).then((r) => r.json());
const PAGE_SIZE = 20;

// New Customer Registrations — list view, generated by RNC from the UIR.
export default function NewCustomerRegistrationsPage() {
  const [page, setPage] = useState(1);
  const [query, setQuery] = useState("");
  const { data, isLoading } = useSWR(`/api/new_customer_registrations?page=${page}&limit=${PAGE_SIZE}`, fetcher);

  const rows: any[] = data?.data ?? [];
  const total: number = data?.total ?? 0;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  const filtered = query
    ? rows.filter((row) =>
        Object.values(row).some((v) => String(v ?? "").toLowerCase().includes(query.toLowerCase())),
      )
    : rows;

  return (
    <div className="container mx-auto max-w-6xl px-4 py-8">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">New Customer Registrations</h1>
          <p className="text-sm text-muted-foreground">{total} record{total === 1 ? "" : "s"}</p>
        </div>
        <Button asChild>
          <Link href="/new_customer_registrations/new"><Plus className="h-4 w-4" /> New Register Now Customer</Link>
        </Button>
      </div>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between gap-4 space-y-0">
          <CardTitle className="text-base">All New Customer Registrations</CardTitle>
          <div className="relative w-full max-w-xs">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="pl-8"
            />
          </div>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-2">
              <Skeleton className="h-10 w-full" />
              <Skeleton className="h-10 w-full" />
              <Skeleton className="h-10 w-full" />
            </div>
          ) : filtered.length === 0 ? (
            <div className="flex flex-col items-center justify-center gap-2 py-16 text-center">
              <Inbox className="h-10 w-10 text-muted-foreground" />
              <p className="font-medium">No New Customer Registrations found</p>
              <p className="text-sm text-muted-foreground">
                {query ? "Try a different search." : "Create the first record to get started."}
              </p>
              {!query && (
                <Button asChild variant="outline" className="mt-2">
                  <Link href="/new_customer_registrations/new"><Plus className="h-4 w-4" /> New Register Now Customer</Link>
                </Button>
              )}
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date Of Birth</TableHead>
                  <TableHead>Password</TableHead>
                  <TableHead>Address</TableHead>
                  <TableHead>Government Id Type</TableHead>
                  <TableHead>Phone Number</TableHead>
                  <TableHead>Gender</TableHead>
                  <TableHead>Email</TableHead>
                  <TableHead>Account Type</TableHead>
                  <TableHead>Government Id Number</TableHead>
                  <TableHead>Name</TableHead>
                  <TableHead>Username</TableHead>
                  <TableHead>Image</TableHead>
                  <TableHead>Registration Date</TableHead>
                  <TableHead className="w-0" />
                </TableRow>
              </TableHeader>
              <TableBody>
                {filtered.map((row) => (
                  <TableRow key={row.id}>
                    <TableCell>{String(row.dob ?? "")}</TableCell>
                    <TableCell>{String(row.password ?? "")}</TableCell>
                    <TableCell>{String(row.address ?? "")}</TableCell>
                    <TableCell>{String(row.gvtidType ?? "")}</TableCell>
                    <TableCell>{String(row.phoneno ?? "")}</TableCell>
                    <TableCell>{String(row.gender ?? "")}</TableCell>
                    <TableCell>{String(row.email ?? "")}</TableCell>
                    <TableCell>{String(row.accountType ?? "")}</TableCell>
                    <TableCell>{String(row.gvtidNo ?? "")}</TableCell>
                    <TableCell>{String(row.name ?? "")}</TableCell>
                    <TableCell>{String(row.usernamee ?? "")}</TableCell>
                    <TableCell>{String(row.image ?? "")}</TableCell>
                    <TableCell>{String(row.regDate ?? "")}</TableCell>
                    <TableCell className="text-right">
                      <Button variant="ghost" size="sm" asChild>
                        <Link href={`/new_customer_registrations/${row.id}/edit`}><Pencil className="h-4 w-4" /> Edit</Link>
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {totalPages > 1 && (
        <div className="mt-4 flex items-center justify-end gap-2">
          <span className="text-sm text-muted-foreground">Page {page} of {totalPages}</span>
          <Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>
            Previous
          </Button>
          <Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)}>
            Next
          </Button>
        </div>
      )}
    </div>
  );
}
