"use client";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { pickOrderNoDlgSchema, type PickOrderNoDlgInput } from "@/lib/validation/pickOrderNoDlg";

// Pick Order No Dlg — create/edit form, generated by RNC from the UIR.
export default function PickOrderNoDlgForm() {
  const router = useRouter();
  const { register, handleSubmit, control, formState: { errors, isSubmitting } } =
    useForm<PickOrderNoDlgInput>({ resolver: zodResolver(pickOrderNoDlgSchema) });

  async function onSubmit(values: PickOrderNoDlgInput) {
    const res = await fetch("/api/pick_order_no_dlgs", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/pick_order_no_dlgs");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/pick_order_no_dlgs"><ArrowLeft className="h-4 w-4" /> Back to Pick Order No Dlgs</Link>
      </Button>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Card>
          <CardHeader>
            <CardTitle>Pick Order No Dlg</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <label htmlFor="dblookupListBox1" className="text-sm font-medium">Dblookup List Box</label>
              <Controller
                control={control}
                name={"dblookupListBox1" as never}
                render={({ field }) => (
                  <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                    <SelectTrigger id="dblookupListBox1"><SelectValue placeholder="Select…" /></SelectTrigger>
                    <SelectContent>
                    </SelectContent>
                  </Select>
                )}
              />
              {errors.dblookupListBox1 && <p className="text-sm text-destructive">{String(errors.dblookupListBox1?.message ?? "")}</p>}
            </div>
          </CardContent>
          <CardFooter className="justify-end gap-2">
            <Button type="button" variant="outline" asChild>
              <Link href="/pick_order_no_dlgs">Cancel</Link>
            </Button>
            <Button type="submit" disabled={isSubmitting}>Save</Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  );
}
