"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { ComboboxCreate } from "@/components/ui/combobox-create";
import { ordersSchema, type OrdersInput } from "@/lib/validation/orders";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Lookup field → options fetched live from the referenced entity's API.
function RelationSelect({ route, optionLabel, value, onChange }: {
  route: string; optionLabel: string; value: string; onChange: (v: string) => void;
}) {
  const { data } = useSWR(`/api/${route}?page=1&limit=100`, fetcher);
  const rows: any[] = data?.data ?? [];
  function label(row: any): string {
    if (row[optionLabel] != null && row[optionLabel] !== "") return String(row[optionLabel]);
    for (const [k, v] of Object.entries(row)) {
      if (k === "id" || k.endsWith("Id") || k.endsWith("_id")) continue;
      if (typeof v === "string" && v !== "") return v;
    }
    return String(row.id);
  }
  return (
    <Select value={value ?? ""} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Select…" /></SelectTrigger>
      <SelectContent>
        {rows.map((row) => (
          <SelectItem key={row.id} value={String(row.id)}>{label(row)}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// Ed Order — edit view, generated by RNC from the UIR.
export default function OrdersEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/orders/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<OrdersInput>({ resolver: zodResolver(ordersSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: OrdersInput) {
    const res = await fetch(`/api/orders/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/orders");
  }

  async function onDelete() {
    const res = await fetch(`/api/orders/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/orders");
  }

  return (
    <div className="w-full px-6 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/orders"><ArrowLeft className="h-4 w-4" /> Back to Orders</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Ed Order</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="shiptoaddr1" className="text-sm font-medium">Ship To Addr1</label>
                <Input id="shiptoaddr1" type="text" placeholder="Enter ship to addr1" {...register("shiptoaddr1")} />
                {errors.shiptoaddr1 && <p className="text-sm text-destructive">{String(errors.shiptoaddr1?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shiptoaddr2" className="text-sm font-medium">Ship To Addr2</label>
                <Input id="shiptoaddr2" type="text" placeholder="Enter ship to addr2" {...register("shiptoaddr2")} />
                {errors.shiptoaddr2 && <p className="text-sm text-destructive">{String(errors.shiptoaddr2?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shiptocontact" className="text-sm font-medium">Ship To Contact</label>
                <Input id="shiptocontact" type="text" placeholder="Enter ship to contact" {...register("shiptocontact")} />
                {errors.shiptocontact && <p className="text-sm text-destructive">{String(errors.shiptocontact?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shiptocity" className="text-sm font-medium">Ship To City</label>
                <Input id="shiptocity" type="text" placeholder="Enter ship to city" {...register("shiptocity")} />
                {errors.shiptocity && <p className="text-sm text-destructive">{String(errors.shiptocity?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shiptostate" className="text-sm font-medium">Ship To State</label>
                <Input id="shiptostate" type="text" placeholder="Enter ship to state" {...register("shiptostate")} />
                {errors.shiptostate && <p className="text-sm text-destructive">{String(errors.shiptostate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shiptozip" className="text-sm font-medium">Ship To Zip</label>
                <Input id="shiptozip" type="text" placeholder="Enter ship to zip" {...register("shiptozip")} />
                {errors.shiptozip && <p className="text-sm text-destructive">{String(errors.shiptozip?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="po" className="text-sm font-medium">Po</label>
                <Input id="po" type="text" placeholder="Enter po" {...register("po")} />
                {errors.po && <p className="text-sm text-destructive">{String(errors.po?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="terms" className="text-sm font-medium">Terms</label>
                <Controller
                  control={control}
                  name={"terms" as never}
                  render={({ field }) => (
                    <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                      <SelectTrigger id="terms"><SelectValue placeholder="Select…" /></SelectTrigger>
                      <SelectContent>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.terms && <p className="text-sm text-destructive">{String(errors.terms?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="paymentmethod" className="text-sm font-medium">Payment Method</label>
                <Controller
                  control={control}
                  name={"paymentmethod" as never}
                  render={({ field }) => (
                    <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                      <SelectTrigger id="paymentmethod"><SelectValue placeholder="Select…" /></SelectTrigger>
                      <SelectContent>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.paymentmethod && <p className="text-sm text-destructive">{String(errors.paymentmethod?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shipvia" className="text-sm font-medium">Ship Via</label>
                <Controller
                  control={control}
                  name={"shipvia" as never}
                  render={({ field }) => (
                    <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                      <SelectTrigger id="shipvia"><SelectValue placeholder="Select…" /></SelectTrigger>
                      <SelectContent>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.shipvia && <p className="text-sm text-destructive">{String(errors.shipvia?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="saledate" className="text-sm font-medium">Sale Date</label>
                <Input id="saledate" type="date" {...register("saledate")} />
                {errors.saledate && <p className="text-sm text-destructive">{String(errors.saledate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="amountpaid" className="text-sm font-medium">Amount Paid</label>
                <div className="relative">
                  <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                  <Input id="amountpaid" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("amountpaid", { valueAsNumber: true })} />
                </div>
                {errors.amountpaid && <p className="text-sm text-destructive">{String(errors.amountpaid?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="freight" className="text-sm font-medium">Freight</label>
                <div className="relative">
                  <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                  <Input id="freight" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("freight", { valueAsNumber: true })} />
                </div>
                {errors.freight && <p className="text-sm text-destructive">{String(errors.freight?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="amountdue" className="text-sm font-medium">Amount Due</label>
                <div className="relative">
                  <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                  <Input id="amountdue" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("amountdue", { valueAsNumber: true })} />
                </div>
                {errors.amountdue && <p className="text-sm text-destructive">{String(errors.amountdue?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="taxrate" className="text-sm font-medium">Tax Rate</label>
                <Input id="taxrate" type="text" placeholder="Enter tax rate" {...register("taxrate")} />
                {errors.taxrate && <p className="text-sm text-destructive">{String(errors.taxrate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="empno" className="text-sm font-medium">Emp No</label>
                <Controller
                  control={control}
                  name={"empno" as never}
                  render={({ field }) => (
                    <ComboboxCreate
                      name="empno"
                      route="employees"
                      optionLabel="fullname"
                      createFields={[{"name":"empno","label":"Empno","inputType":"text","required":false},{"name":"fullname","label":"Fullname","inputType":"text","required":false},{"name":"lastname","label":"Lastname","inputType":"text","required":false},{"name":"firstname","label":"Firstname","inputType":"text","required":false},{"name":"phoneext","label":"Phoneext","inputType":"text","required":false},{"name":"hiredate","label":"Hiredate","inputType":"date","required":false},{"name":"salary","label":"Salary","inputType":"text","required":false}]}
                      value={(field.value as string) ?? ""}
                      onChange={field.onChange}
                    />
                  )}
                />
                {errors.empno && <p className="text-sm text-destructive">{String(errors.empno?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="custno" className="text-sm font-medium">Cust No</label>
                <Controller
                  control={control}
                  name={"custno" as never}
                  render={({ field }) => (
                    <ComboboxCreate
                      name="custno"
                      route="customers"
                      optionLabel="company"
                      createFields={[{"name":"custno","label":"Custno","inputType":"text","required":false},{"name":"company","label":"Company","inputType":"text","required":false},{"name":"addr1","label":"Addr1","inputType":"text","required":false},{"name":"addr2","label":"Addr2","inputType":"text","required":false},{"name":"city","label":"City","inputType":"text","required":false},{"name":"state","label":"State","inputType":"text","required":false},{"name":"zip","label":"Zip","inputType":"text","required":false},{"name":"country","label":"Country","inputType":"text","required":false},{"name":"phone","label":"Phone","inputType":"text","required":false},{"name":"fax","label":"Fax","inputType":"text","required":false},{"name":"taxrate","label":"Taxrate","inputType":"text","required":false},{"name":"contact","label":"Contact","inputType":"text","required":false},{"name":"lastinvoicedate","label":"Lastinvoicedate","inputType":"date","required":false}]}
                      value={(field.value as string) ?? ""}
                      onChange={field.onChange}
                    />
                  )}
                />
                {errors.custno && <p className="text-sm text-destructive">{String(errors.custno?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
