"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { ComboboxCreate } from "@/components/ui/combobox-create";
import { ordersSchema, type OrdersInput } from "@/lib/validation/orders";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Lookup field → options fetched live from the referenced entity's API.
function RelationSelect({ route, optionLabel, value, onChange }: {
  route: string; optionLabel: string; value: string; onChange: (v: string) => void;
}) {
  const { data } = useSWR(`/api/${route}?page=1&limit=100`, fetcher);
  const rows: any[] = data?.data ?? [];
  function label(row: any): string {
    if (row[optionLabel] != null && row[optionLabel] !== "") return String(row[optionLabel]);
    for (const [k, v] of Object.entries(row)) {
      if (k === "id" || k.endsWith("Id") || k.endsWith("_id")) continue;
      if (typeof v === "string" && v !== "") return v;
    }
    return String(row.id);
  }
  return (
    <Select value={value ?? ""} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Select…" /></SelectTrigger>
      <SelectContent>
        {rows.map((row) => (
          <SelectItem key={row.id} value={String(row.id)}>{label(row)}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// Ed Order — edit view, generated by RNC from the UIR.
export default function OrdersEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/orders/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<OrdersInput>({ resolver: zodResolver(ordersSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: OrdersInput) {
    const res = await fetch(`/api/orders/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/orders");
  }

  async function onDelete() {
    const res = await fetch(`/api/orders/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/orders");
  }

  return (
    <div className="w-full px-6 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/orders"><ArrowLeft className="h-4 w-4" /> Back to Orders</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Ed Order</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="shipToAddr1" className="text-sm font-medium">Ship To Addr1</label>
                <Input id="shipToAddr1" type="text" placeholder="Enter ship to addr1" {...register("shipToAddr1")} />
                {errors.shipToAddr1 && <p className="text-sm text-destructive">{String(errors.shipToAddr1?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shipToAddr2" className="text-sm font-medium">Ship To Addr2</label>
                <Input id="shipToAddr2" type="text" placeholder="Enter ship to addr2" {...register("shipToAddr2")} />
                {errors.shipToAddr2 && <p className="text-sm text-destructive">{String(errors.shipToAddr2?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shipToContact" className="text-sm font-medium">Ship To Contact</label>
                <Input id="shipToContact" type="text" placeholder="Enter ship to contact" {...register("shipToContact")} />
                {errors.shipToContact && <p className="text-sm text-destructive">{String(errors.shipToContact?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shipToCity" className="text-sm font-medium">Ship To City</label>
                <Input id="shipToCity" type="text" placeholder="Enter ship to city" {...register("shipToCity")} />
                {errors.shipToCity && <p className="text-sm text-destructive">{String(errors.shipToCity?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shipToState" className="text-sm font-medium">Ship To State</label>
                <Input id="shipToState" type="text" placeholder="Enter ship to state" {...register("shipToState")} />
                {errors.shipToState && <p className="text-sm text-destructive">{String(errors.shipToState?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shipToZip" className="text-sm font-medium">Ship To Zip</label>
                <Input id="shipToZip" type="text" placeholder="Enter ship to zip" {...register("shipToZip")} />
                {errors.shipToZip && <p className="text-sm text-destructive">{String(errors.shipToZip?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="po" className="text-sm font-medium">Po</label>
                <Input id="po" type="text" placeholder="Enter po" {...register("po")} />
                {errors.po && <p className="text-sm text-destructive">{String(errors.po?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="terms" className="text-sm font-medium">Terms</label>
                <Controller
                  control={control}
                  name={"terms" as never}
                  render={({ field }) => (
                    <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                      <SelectTrigger id="terms"><SelectValue placeholder="Select…" /></SelectTrigger>
                      <SelectContent>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.terms && <p className="text-sm text-destructive">{String(errors.terms?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="paymentMethod" className="text-sm font-medium">Payment Method</label>
                <Controller
                  control={control}
                  name={"paymentMethod" as never}
                  render={({ field }) => (
                    <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                      <SelectTrigger id="paymentMethod"><SelectValue placeholder="Select…" /></SelectTrigger>
                      <SelectContent>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.paymentMethod && <p className="text-sm text-destructive">{String(errors.paymentMethod?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="shipVia" className="text-sm font-medium">Ship Via</label>
                <Controller
                  control={control}
                  name={"shipVia" as never}
                  render={({ field }) => (
                    <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                      <SelectTrigger id="shipVia"><SelectValue placeholder="Select…" /></SelectTrigger>
                      <SelectContent>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.shipVia && <p className="text-sm text-destructive">{String(errors.shipVia?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="saleDate" className="text-sm font-medium">Sale Date</label>
                <Input id="saleDate" type="date" {...register("saleDate")} />
                {errors.saleDate && <p className="text-sm text-destructive">{String(errors.saleDate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="amountPaid" className="text-sm font-medium">Amount Paid</label>
                <div className="relative">
                  <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                  <Input id="amountPaid" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("amountPaid", { valueAsNumber: true })} />
                </div>
                {errors.amountPaid && <p className="text-sm text-destructive">{String(errors.amountPaid?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="freight" className="text-sm font-medium">Freight</label>
                <Input id="freight" type="text" placeholder="Enter freight" {...register("freight")} />
                {errors.freight && <p className="text-sm text-destructive">{String(errors.freight?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="amountDue" className="text-sm font-medium">Amount Due</label>
                <div className="relative">
                  <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                  <Input id="amountDue" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("amountDue", { valueAsNumber: true })} />
                </div>
                {errors.amountDue && <p className="text-sm text-destructive">{String(errors.amountDue?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="taxRate" className="text-sm font-medium">Tax Rate</label>
                <div className="relative">
                  <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                  <Input id="taxRate" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("taxRate", { valueAsNumber: true })} />
                </div>
                {errors.taxRate && <p className="text-sm text-destructive">{String(errors.taxRate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="empNo" className="text-sm font-medium">Emp No</label>
                <Controller
                  control={control}
                  name={"empNo" as never}
                  render={({ field }) => (
                    <ComboboxCreate
                      name="empNo"
                      route="employees"
                      optionLabel="fullname"
                      createFields={[{"name":"empno","label":"Empno","inputType":"text","required":false},{"name":"fullname","label":"Fullname","inputType":"text","required":false},{"name":"lastname","label":"Lastname","inputType":"text","required":false},{"name":"firstname","label":"Firstname","inputType":"text","required":false},{"name":"phoneext","label":"Phoneext","inputType":"text","required":false},{"name":"hiredate","label":"Hiredate","inputType":"date","required":false},{"name":"salary","label":"Salary","inputType":"text","required":false}]}
                      value={(field.value as string) ?? ""}
                      onChange={field.onChange}
                    />
                  )}
                />
                {errors.empNo && <p className="text-sm text-destructive">{String(errors.empNo?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="custNo" className="text-sm font-medium">Cust No</label>
                <Controller
                  control={control}
                  name={"custNo" as never}
                  render={({ field }) => (
                    <ComboboxCreate
                      name="custNo"
                      route="customers"
                      optionLabel="company"
                      createFields={[{"name":"custno","label":"Custno","inputType":"text","required":false},{"name":"company","label":"Company","inputType":"text","required":false},{"name":"addr1","label":"Addr1","inputType":"text","required":false},{"name":"addr2","label":"Addr2","inputType":"text","required":false},{"name":"city","label":"City","inputType":"text","required":false},{"name":"state","label":"State","inputType":"text","required":false},{"name":"zip","label":"Zip","inputType":"text","required":false},{"name":"country","label":"Country","inputType":"text","required":false},{"name":"phone","label":"Phone","inputType":"text","required":false},{"name":"fax","label":"Fax","inputType":"text","required":false},{"name":"taxrate","label":"Taxrate","inputType":"text","required":false},{"name":"contact","label":"Contact","inputType":"text","required":false},{"name":"lastinvoicedate","label":"Lastinvoicedate","inputType":"date","required":false}]}
                      value={(field.value as string) ?? ""}
                      onChange={field.onChange}
                    />
                  )}
                />
                {errors.custNo && <p className="text-sm text-destructive">{String(errors.custNo?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="custNo" className="text-sm font-medium">Cust No</label>
                <Controller
                  control={control}
                  name={"custNo" as never}
                  render={({ field }) => (
                    <ComboboxCreate
                      name="custNo"
                      route="customers"
                      optionLabel="id"
                      createFields={[{"name":"custno","label":"Custno","inputType":"text","required":false},{"name":"company","label":"Company","inputType":"text","required":false},{"name":"addr1","label":"Addr1","inputType":"text","required":false},{"name":"addr2","label":"Addr2","inputType":"text","required":false},{"name":"city","label":"City","inputType":"text","required":false},{"name":"state","label":"State","inputType":"text","required":false},{"name":"zip","label":"Zip","inputType":"text","required":false},{"name":"country","label":"Country","inputType":"text","required":false},{"name":"phone","label":"Phone","inputType":"text","required":false},{"name":"fax","label":"Fax","inputType":"text","required":false},{"name":"taxrate","label":"Taxrate","inputType":"text","required":false},{"name":"contact","label":"Contact","inputType":"text","required":false},{"name":"lastinvoicedate","label":"Lastinvoicedate","inputType":"date","required":false}]}
                      value={(field.value as string) ?? ""}
                      onChange={field.onChange}
                    />
                  )}
                />
                {errors.custNo && <p className="text-sm text-destructive">{String(errors.custNo?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
