"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { customerDetailsSchema, type CustomerDetailsInput } from "@/lib/validation/customerDetails";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Customer Dashboars Yt Bank Of India — edit view, generated by RNC from the UIR.
export default function CustomerDetailsEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/customer_details/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<CustomerDetailsInput>({ resolver: zodResolver(customerDetailsSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: CustomerDetailsInput) {
    const res = await fetch(`/api/customer_details/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/customer_details");
  }

  async function onDelete() {
    const res = await fetch(`/api/customer_details/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/customer_details");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/customer_details"><ArrowLeft className="h-4 w-4" /> Back to Customer Details</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Customer Dashboars Yt Bank Of India</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="accountNo" className="text-sm font-medium">Account No</label>
                <Input id="accountNo" type="text" placeholder="Enter account no" {...register("accountNo")} />
                {errors.accountNo && <p className="text-sm text-destructive">{String(errors.accountNo?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="accountBallance" className="text-sm font-medium">Account Balance</label>
                <Input id="accountBallance" type="text" placeholder="Enter account balance" {...register("accountBallance")} />
                {errors.accountBallance && <p className="text-sm text-destructive">{String(errors.accountBallance?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="name" className="text-sm font-medium">Name</label>
                <Input id="name" type="text" placeholder="Enter name" {...register("name")} />
                {errors.name && <p className="text-sm text-destructive">{String(errors.name?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
