"use client";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { newCustomerRegistrationSchema, type NewCustomerRegistrationInput } from "@/lib/validation/newCustomerRegistration";

// Register Now Customer — create/edit form, generated by RNC from the UIR.
export default function NewCustomerRegistrationForm() {
  const router = useRouter();
  const { register, handleSubmit, control, formState: { errors, isSubmitting } } =
    useForm<NewCustomerRegistrationInput>({ resolver: zodResolver(newCustomerRegistrationSchema) });

  async function onSubmit(values: NewCustomerRegistrationInput) {
    const res = await fetch("/api/new_customer_registrations", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/new_customer_registrations");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/new_customer_registrations"><ArrowLeft className="h-4 w-4" /> Back to New Customer Registrations</Link>
      </Button>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Card>
          <CardHeader>
            <CardTitle>Register Now Customer</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <label htmlFor="dob" className="text-sm font-medium">Date Of Birth</label>
              <Input id="dob" type="text" placeholder="Enter date of birth" {...register("dob")} />
              {errors.dob && <p className="text-sm text-destructive">{String(errors.dob?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="password" className="text-sm font-medium">Password</label>
              <Input id="password" type="password" placeholder="Enter password" {...register("password")} />
              {errors.password && <p className="text-sm text-destructive">{String(errors.password?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="address" className="text-sm font-medium">Address</label>
              <Input id="address" type="text" placeholder="Enter address" {...register("address")} />
              {errors.address && <p className="text-sm text-destructive">{String(errors.address?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="gvtidType" className="text-sm font-medium">Government Id Type</label>
              <Input id="gvtidType" type="text" placeholder="Enter government id type" {...register("gvtidType")} />
              {errors.gvtidType && <p className="text-sm text-destructive">{String(errors.gvtidType?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="phoneno" className="text-sm font-medium">Phone Number</label>
              <Input id="phoneno" type="tel" placeholder="Enter phone number" {...register("phoneno")} />
              {errors.phoneno && <p className="text-sm text-destructive">{String(errors.phoneno?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="gender" className="text-sm font-medium">Gender</label>
              <Input id="gender" type="text" placeholder="Enter gender" {...register("gender")} />
              {errors.gender && <p className="text-sm text-destructive">{String(errors.gender?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="email" className="text-sm font-medium">Email</label>
              <Input id="email" type="email" placeholder="Enter email" {...register("email")} />
              {errors.email && <p className="text-sm text-destructive">{String(errors.email?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="accountType" className="text-sm font-medium">Account Type</label>
              <Input id="accountType" type="text" placeholder="Enter account type" {...register("accountType")} />
              {errors.accountType && <p className="text-sm text-destructive">{String(errors.accountType?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="gvtidNo" className="text-sm font-medium">Government Id Number</label>
              <Input id="gvtidNo" type="text" placeholder="Enter government id number" {...register("gvtidNo")} />
              {errors.gvtidNo && <p className="text-sm text-destructive">{String(errors.gvtidNo?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="name" className="text-sm font-medium">Name</label>
              <Input id="name" type="text" placeholder="Enter name" {...register("name")} />
              {errors.name && <p className="text-sm text-destructive">{String(errors.name?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="usernamee" className="text-sm font-medium">Username</label>
              <Input id="usernamee" type="text" placeholder="Enter username" {...register("usernamee")} />
              {errors.usernamee && <p className="text-sm text-destructive">{String(errors.usernamee?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="image" className="text-sm font-medium">Image</label>
              <Input id="image" type="text" placeholder="Enter image" {...register("image")} />
              {errors.image && <p className="text-sm text-destructive">{String(errors.image?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="regDate" className="text-sm font-medium">Registration Date</label>
              <Input id="regDate" type="tel" placeholder="Enter registration date" {...register("regDate")} />
              {errors.regDate && <p className="text-sm text-destructive">{String(errors.regDate?.message ?? "")}</p>}
            </div>
          </CardContent>
          <CardFooter className="justify-end gap-2">
            <Button type="button" variant="outline" asChild>
              <Link href="/new_customer_registrations">Cancel</Link>
            </Button>
            <Button type="submit" disabled={isSubmitting}>Save</Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  );
}
