"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { newCustomerRegistrationSchema, type NewCustomerRegistrationInput } from "@/lib/validation/newCustomerRegistration";

// Register Now Customer — create/edit form, generated by RNC from the UIR.
export default function NewCustomerRegistrationForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<NewCustomerRegistrationInput>({ resolver: zodResolver(newCustomerRegistrationSchema) });

  async function onSubmit(values: NewCustomerRegistrationInput) {
    const res = await fetch("/api/new_customer_registrations", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/new_customer_registrations");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Register Now Customer</h1>
      <div className="space-y-1">
        <label htmlFor="dob" className="text-sm font-medium">dob</label>
        <Input id="dob" type="text" placeholder="Enter dob" {...register("dob")} />
        {errors.dob && <p className="text-sm text-red-500">{String(errors.dob?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="password" className="text-sm font-medium">pwText</label>
        <Input id="password" type="password" placeholder="Enter pwtext" {...register("password")} />
        {errors.password && <p className="text-sm text-red-500">{String(errors.password?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="address" className="text-sm font-medium">addressText</label>
        <Input id="address" type="text" placeholder="Enter addresstext" {...register("address")} />
        {errors.address && <p className="text-sm text-red-500">{String(errors.address?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="gvtidType" className="text-sm font-medium">gvtidCombo</label>
        <Input id="gvtidType" type="text" placeholder="Enter gvtidcombo" {...register("gvtidType")} />
        {errors.gvtidType && <p className="text-sm text-red-500">{String(errors.gvtidType?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="phoneno" className="text-sm font-medium">phoneText</label>
        <Input id="phoneno" type="tel" placeholder="Enter phonetext" {...register("phoneno")} />
        {errors.phoneno && <p className="text-sm text-red-500">{String(errors.phoneno?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="gender" className="text-sm font-medium">genderCombo</label>
        <Input id="gender" type="text" placeholder="Enter gendercombo" {...register("gender")} />
        {errors.gender && <p className="text-sm text-red-500">{String(errors.gender?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="email" className="text-sm font-medium">emailText</label>
        <Input id="email" type="email" placeholder="Enter emailtext" {...register("email")} />
        {errors.email && <p className="text-sm text-red-500">{String(errors.email?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountType" className="text-sm font-medium">AccuuntCombo</label>
        <Input id="accountType" type="text" placeholder="Enter accuuntcombo" {...register("accountType")} />
        {errors.accountType && <p className="text-sm text-red-500">{String(errors.accountType?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="gvtidNo" className="text-sm font-medium">govtidnoText</label>
        <Input id="gvtidNo" type="text" placeholder="Enter govtidnotext" {...register("gvtidNo")} />
        {errors.gvtidNo && <p className="text-sm text-red-500">{String(errors.gvtidNo?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="name" className="text-sm font-medium">nameText</label>
        <Input id="name" type="text" placeholder="Enter nametext" {...register("name")} />
        {errors.name && <p className="text-sm text-red-500">{String(errors.name?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="usernamee" className="text-sm font-medium">usernameText</label>
        <Input id="usernamee" type="text" placeholder="Enter usernametext" {...register("usernamee")} />
        {errors.usernamee && <p className="text-sm text-red-500">{String(errors.usernamee?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="image" className="text-sm font-medium">showimglink</label>
        <Input id="image" type="text" placeholder="Enter showimglink" {...register("image")} />
        {errors.image && <p className="text-sm text-red-500">{String(errors.image?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="regDate" className="text-sm font-medium">datelabel</label>
        <Input id="regDate" type="tel" placeholder="Enter datelabel" {...register("regDate")} />
        {errors.regDate && <p className="text-sm text-red-500">{String(errors.regDate?.message ?? "")}</p>}
      </div>
      <Button type="submit">Save</Button>
    </form>
  );
}
