"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { helpSchema, type HelpInput } from "@/lib/validation/help";

// Help — create/edit form, generated by RNC from the UIR.
export default function HelpForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<HelpInput>({ resolver: zodResolver(helpSchema) });

  async function onSubmit(values: HelpInput) {
    const res = await fetch("/api/helps", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/helps");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Help</h1>
      <Button type="submit">Save</Button>
    </form>
  );
}
