import { z } from "zod";

// Validation schema for AdminDetails — generated by RNC from the UIR.
export const adminDetailsSchema = z.object({
  name: z.string().nullish(),
  email: z.string().nullish(),
  pin: z.string().nullish(),
  phoneno: z.string().nullish(),
  image: z.string().nullish(),
  doj: z.coerce.date().nullish(),
  id: z.string().nullish(),
  address: z.string().nullish(),
  gender: z.string().nullish(),
});

export type AdminDetailsInput = z.infer<typeof adminDetailsSchema>;
