import { z } from "zod";

// Validation schema for Atribuicao — generated by RNC from the UIR.
export const atribuicaoSchema = z.object({
  versao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.number().int().default(1)),
  dataUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.date().default(() => new Date())),
  usuarioUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.string().min(1).default("app")),
  avocar: z.coerce.number().int().nullish(),
  avocar2: z.coerce.number().int().nullish(),
  avocar3: z.coerce.number().int().nullish(),
  delegar: z.coerce.number().int().nullish(),
  funcionario: z.coerce.number().int(),
  responderPor: z.coerce.number().int().nullish(),
});

export type AtribuicaoInput = z.infer<typeof atribuicaoSchema>;
