import { z } from "zod";

// Validation schema for AuditoriaDetalhadaFuncionario — generated by RNC from the UIR.
export const auditoriaDetalhadaFuncionarioSchema = z.object({
  id: z.coerce.number().int(),
  tabela: z.string().min(1),
  data: z.coerce.date(),
  nfFuncionario: z.string().nullish(),
  evento: z.string().nullish(),
  observacao: z.string().nullish(),
  dataUltAlteracao: z.coerce.date(),
  usuarioUltAlteracao: z.string().min(1),
  versao: z.coerce.number().int(),
  nfFuncionario: z.string().nullish(),
});

export type AuditoriaDetalhadaFuncionarioInput = z.infer<typeof auditoriaDetalhadaFuncionarioSchema>;
