import { z } from "zod";

// Validation schema for Auditoria — generated by RNC from the UIR.
export const auditoriaSchema = z.object({
  numAuditoria: z.coerce.number().nullish(),
  dtEvento: z.coerce.number().nullish(),
  hrEvento: z.coerce.number().nullish(),
  tsEvento: z.coerce.number().nullish(),
  codAcao: z.string().nullish(),
  codModulo: z.string().nullish(),
  desAcao: z.string().nullish(),
  tipoEntidade: z.string().nullish(),
  idEntidade: z.string().nullish(),
  numCpfAfetado: z.string().nullish(),
  usrEvento: z.string().nullish(),
  nomeUsuario: z.string().nullish(),
  codPerfil: z.string().nullish(),
  codLotacao: z.string().nullish(),
  ipOrigem: z.string().nullish(),
  idSessao: z.string().nullish(),
  numCicloBatch: z.coerce.number().nullish(),
  numSeqBatch: z.coerce.number().nullish(),
  nomJobBatch: z.string().nullish(),
  sitBatch: z.string().nullish(),
  desErroBatch: z.string().nullish(),
  idCorrelacao: z.string().nullish(),
  numSeqCorrelacao: z.coerce.number().nullish(),
});

export type AuditoriaInput = z.infer<typeof auditoriaSchema>;
