import { z } from "zod";

// Validation schema for AuditoriaDetalhadaFuncionario — generated by RNC from the UIR.
export const auditoriaDetalhadaFuncionarioSchema = z.object({
  tabela: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  data: z.coerce.date(),
  nfFuncionario: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().nullish()),
  evento: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().nullish()),
  observacao: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().nullish()),
  dataUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.date().default(() => new Date())),
  usuarioUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.string().min(1).default("app")),
  versao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.number().int().default(1)),
});

export type AuditoriaDetalhadaFuncionarioInput = z.infer<typeof auditoriaDetalhadaFuncionarioSchema>;
