import { z } from "zod";

// Validation schema for BeneficiarioGrpDependente — generated by RNC from the UIR.
export const beneficiarioGrpDependenteSchema = z.object({
  occurrence: z.coerce.number().int(),
  cpfDependente: z.string().nullish(),
  nomeDependente: z.string().nullish(),
  dtNascDepend: z.coerce.number().nullish(),
  parentesco: z.string().nullish(),
  sitDependente: z.string().nullish(),
  indDeficiencia: z.string().nullish(),
});

export type BeneficiarioGrpDependenteInput = z.infer<typeof beneficiarioGrpDependenteSchema>;
