import { z } from "zod";

// Validation schema for Curso — generated by RNC from the UIR.
export const cursoSchema = z.object({
  id: z.coerce.number().int(),
  abvCurso: z.string().min(1),
  nomeCurso: z.string().min(1),
  ativo: z.string().min(1),
  interesseCorporacao: z.string().min(1),
  dataUltAlteracao: z.coerce.date(),
  usuarioUltAlteracao: z.string().min(1),
  versao: z.coerce.number().int(),
  abvCurso: z.string().min(1),
  interesseCorporacao: z.string().min(1),
  nomeCurso: z.string().min(1),
});

export type CursoInput = z.infer<typeof cursoSchema>;
