import { z } from "zod";

// Validation schema for Customer — generated by RNC from the UIR.
export const customerSchema = z.object({
  custno: z.coerce.number().nullish(),
  company: z.string().nullish(),
  addr1: z.string().nullish(),
  addr2: z.string().nullish(),
  city: z.string().nullish(),
  state: z.string().nullish(),
  zip: z.string().nullish(),
  country: z.string().nullish(),
  phone: z.string().nullish(),
  fax: z.string().nullish(),
  taxrate: z.coerce.number().nullish(),
  contact: z.string().nullish(),
  lastinvoicedate: z.coerce.date().nullish(),
});

export type CustomerInput = z.infer<typeof customerSchema>;
