import { z } from "zod";

// Validation schema for CustomerDetails — generated by RNC from the UIR.
export const customerDetailsSchema = z.object({
  accountNo: z.string().nullish(),
  accountBallance: z.coerce.number().nullish(),
  name: z.string().nullish(),
  dob: z.coerce.date().nullish(),
  gvtidNo: z.string().nullish(),
  gvtidType: z.string().nullish(),
  phoneno: z.string().nullish(),
  image: z.string().nullish(),
  gender: z.string().nullish(),
  regDate: z.coerce.date().nullish(),
  address: z.string().nullish(),
  email: z.string().nullish(),
  accountType: z.string().nullish(),
});

export type CustomerDetailsInput = z.infer<typeof customerDetailsSchema>;
