import { z } from "zod";

// Validation schema for Deposite — generated by RNC from the UIR.
export const depositeSchema = z.object({
  dpositeTime: z.coerce.date().nullish(),
  accountNo: z.string().nullish(),
  macId: z.string().nullish(),
  transactionId: z.string().nullish(),
  ballanceBeforeDeposite: z.coerce.number().nullish(),
  newTotalBallance: z.coerce.number().nullish(),
  depositeBallance: z.coerce.number().nullish(),
  depositeDate: z.coerce.date().nullish(),
});

export type DepositeInput = z.infer<typeof depositeSchema>;
