import { z } from "zod";

// Validation schema for Employee — generated by RNC from the UIR.
export const employeeSchema = z.object({
  empno: z.coerce.number().int().nullish(),
  fullname: z.string().nullish(),
  lastname: z.string().nullish(),
  firstname: z.string().nullish(),
  phoneext: z.string().nullish(),
  hiredate: z.coerce.date().nullish(),
  salary: z.coerce.number().nullish(),
});

export type EmployeeInput = z.infer<typeof employeeSchema>;
