import { z } from "zod";

// Validation schema for FuncaoQdi — generated by RNC from the UIR.
export const funcaoQdiSchema = z.object({
  nomeFuncao: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  nomeFuncaoSiarhes: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().nullish()),
  ativo: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  geral: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  gratificada: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  dataUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.date().default(() => new Date())),
  usuarioUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.string().min(1).default("app")),
  versao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.number().int().default(1)),
});

export type FuncaoQdiInput = z.infer<typeof funcaoQdiSchema>;
