import { z } from "zod";

// Validation schema for FuncaoQdi — generated by RNC from the UIR.
export const funcaoQdiSchema = z.object({
  id: z.coerce.number().int(),
  nomeFuncao: z.string().min(1),
  nomeFuncaoSiarhes: z.string().nullish(),
  ativo: z.string().min(1),
  geral: z.string().min(1),
  gratificada: z.string().min(1),
  dataUltAlteracao: z.coerce.date(),
  usuarioUltAlteracao: z.string().min(1),
  versao: z.coerce.number().int(),
  nomeFuncao: z.string().min(1),
  nomeFuncaosiarhes: z.string().nullish(),
});

export type FuncaoQdiInput = z.infer<typeof funcaoQdiSchema>;
