import { z } from "zod";

// Validation schema for Habilitacao — generated by RNC from the UIR.
export const habilitacaoSchema = z.object({
  descHabilitacao: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  dataUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.date().default(() => new Date())),
  usuarioUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.string().min(1).default("app")),
  versao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.number().int().default(1)),
  tipoHabilitacao: z.coerce.number().int().nullish(),
});

export type HabilitacaoInput = z.infer<typeof habilitacaoSchema>;
