import { z } from "zod";

// Validation schema for Items — generated by RNC from the UIR.
export const itemsSchema = z.object({
  itemno: z.coerce.number().nullish(),
  orderno: z.coerce.number().nullish(),
  description: z.string().nullish(),
  sellprice: z.coerce.number().nullish(),
  qty: z.coerce.number().int().nullish(),
  discount: z.coerce.number().nullish(),
  extprice: z.coerce.number().nullish(),
  partno: z.coerce.number().nullish(),
});

export type ItemsInput = z.infer<typeof itemsSchema>;
