import { z } from "zod";

// Validation schema for Lotacao — generated by RNC from the UIR.
export const lotacaoSchema = z.object({
  id: z.coerce.number().int(),
  funcionarioAuxLookup: z.string().nullish(),
  dataInicio: z.coerce.date().nullish(),
  dataFim: z.coerce.date().nullish(),
  atual: z.string().nullish(),
  substituicao: z.string().nullish(),
  ativo: z.string().nullish(),
  obs: z.string().nullish(),
});

export type LotacaoInput = z.infer<typeof lotacaoSchema>;
