import { z } from "zod";

// Validation schema for MesAnoFerias — generated by RNC from the UIR.
export const mesAnoFeriasSchema = z.object({
  id: z.coerce.number().int(),
  mes: z.string().min(1),
  ano: z.coerce.number().int(),
  funcionario: z.string().nullish(),
});

export type MesAnoFeriasInput = z.infer<typeof mesAnoFeriasSchema>;
