import { z } from "zod";

// Validation schema for Nccruise — generated by RNC from the UIR.
export const nccruiseSchema = z.object({
  cruiseStatus: z.string().min(1),
  startDate: z.coerce.number().nullish(),
  startTime: z.coerce.number(),
  endDate: z.coerce.number(),
  endTime: z.coerce.number(),
  startHarbor: z.string().nullish(),
  destinationHarbor: z.string().nullish(),
  idYacht: z.coerce.number(),
  price1W: z.coerce.number(),
  price2W: z.coerce.number(),
  price3W: z.coerce.number(),
});

export type NccruiseInput = z.infer<typeof nccruiseSchema>;
