import { z } from "zod";

// Validation schema for Ncyacht — generated by RNC from the UIR.
export const ncyachtSchema = z.object({
  yachtName: z.string().min(1),
  yachtType: z.string().min(1),
  length: z.coerce.number(),
  width: z.coerce.number(),
  draft: z.coerce.number(),
  sailSurface: z.coerce.number(),
  motor: z.coerce.number(),
  headRoom: z.coerce.number(),
  bunks: z.coerce.number(),
});

export type NcyachtInput = z.infer<typeof ncyachtSchema>;
