import { z } from "zod";

// Validation schema for NewCustomerRegistration — generated by RNC from the UIR.
export const newCustomerRegistrationSchema = z.object({
  dob: z.coerce.date().nullish(),
  password: z.string().nullish(),
  address: z.string().nullish(),
  gvtidType: z.string().nullish(),
  phoneno: z.string().nullish(),
  gender: z.string().nullish(),
  email: z.string().nullish(),
  accountType: z.string().nullish(),
  gvtidNo: z.string().nullish(),
  name: z.string().nullish(),
  usernamee: z.string().nullish(),
  image: z.string().nullish(),
  regDate: z.coerce.date().nullish(),
});

export type NewCustomerRegistrationInput = z.infer<typeof newCustomerRegistrationSchema>;
