import { z } from "zod";

// Validation schema for Nextcust — generated by RNC from the UIR.
export const nextcustSchema = z.object({
  newcust: z.coerce.number().nullish(),
});

export type NextcustInput = z.infer<typeof nextcustSchema>;
