import { z } from "zod";

// Validation schema for Nextord — generated by RNC from the UIR.
export const nextordSchema = z.object({
  newkey: z.coerce.number().nullish(),
});

export type NextordInput = z.infer<typeof nextordSchema>;
