import { z } from "zod";

// Validation schema for Orders — generated by RNC from the UIR.
export const ordersSchema = z.object({
  orderno: z.coerce.number().nullish(),
  custno: z.coerce.number(),
  saledate: z.coerce.date().nullish(),
  shipdate: z.coerce.date().nullish(),
  shiptocontact: z.string().nullish(),
  shiptoaddr1: z.string().nullish(),
  shiptoaddr2: z.string().nullish(),
  shiptocity: z.string().nullish(),
  shiptostate: z.string().nullish(),
  shiptozip: z.string().nullish(),
  shiptocountry: z.string().nullish(),
  shiptophone: z.string().nullish(),
  shipvia: z.string().nullish(),
  po: z.string().nullish(),
  empno: z.coerce.number().int(),
  terms: z.string().nullish(),
  paymentmethod: z.string().nullish(),
  itemstotal: z.coerce.number().nullish(),
  taxrate: z.coerce.number().nullish(),
  taxtotal: z.coerce.number().nullish(),
  freight: z.coerce.number().nullish(),
  amountpaid: z.coerce.number().nullish(),
  amountdue: z.coerce.number().nullish(),
  salesperson: z.string().nullish(),
});

export type OrdersInput = z.infer<typeof ordersSchema>;
