import { z } from "zod";

// Validation schema for PagamentoGrpDesconto — generated by RNC from the UIR.
export const pagamentoGrpDescontoSchema = z.object({
  occurrence: z.coerce.number().int(),
  tipoDesconto: z.string().nullish(),
  vlrDesconto: z.coerce.number().nullish(),
  pctDesconto: z.coerce.number().nullish(),
  numProcesso: z.string().nullish(),
  dtInicioDsct: z.coerce.number().nullish(),
  dtFimDsct: z.coerce.number().nullish(),
});

export type PagamentoGrpDescontoInput = z.infer<typeof pagamentoGrpDescontoSchema>;
