import { z } from "zod";

// Validation schema for Parts — generated by RNC from the UIR.
export const partsSchema = z.object({
  partno: z.coerce.number(),
  description: z.string().min(1),
  onhand: z.coerce.number().nullish(),
  onorder: z.coerce.number().nullish(),
  vendorno: z.coerce.number().int().nullish(),
  cost: z.coerce.number().nullish(),
  listprice: z.coerce.number().nullish(),
  backord: z.coerce.boolean().nullish(),
});

export type PartsInput = z.infer<typeof partsSchema>;
