import { z } from "zod";

// Validation schema for PickOrderNoDlg — generated by RNC from the UIR.
export const pickOrderNoDlgSchema = z.object({
  dblookupListBox1: z.string().nullish(),
});

export type PickOrderNoDlgInput = z.infer<typeof pickOrderNoDlgSchema>;
