import { z } from "zod";

// Validation schema for PostoGraduacao — generated by RNC from the UIR.
export const postoGraduacaoSchema = z.object({
  abreviacao: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  descricao: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  numeroOrdem: z.coerce.number().int().nullish(),
  codigoSiarhes: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().nullish()),
  praca: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().nullish()),
  oficial: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().nullish()),
  dataUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.date().default(() => new Date())),
  usuarioUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.string().min(1).default("app")),
  versao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.number().int().default(1)),
  postoGradUnificado: z.coerce.number().int().nullish(),
});

export type PostoGraduacaoInput = z.infer<typeof postoGraduacaoSchema>;
