import { z } from "zod";

// Validation schema for ProgramaSocialGrpParamRegional — generated by RNC from the UIR.
export const programaSocialGrpParamRegionalSchema = z.object({
  occurrence: z.coerce.number().int(),
  codRegiao: z.string().nullish(),
  fatorRegional: z.coerce.number().nullish(),
  vlrComplementoReg: z.coerce.number().nullish(),
  indAtivoRegiao: z.string().nullish(),
});

export type ProgramaSocialGrpParamRegionalInput = z.infer<typeof programaSocialGrpParamRegionalSchema>;
