import { z } from "zod";

// Validation schema for ProgramaSocial — generated by RNC from the UIR.
export const programaSocialSchema = z.object({
  codPrograma: z.string().nullish(),
  nomePrograma: z.string().nullish(),
  siglaPrograma: z.string().nullish(),
  tipoPrograma: z.string().nullish(),
  orgaoResponsavel: z.string().nullish(),
  leiCriacao: z.string().nullish(),
  dtCriacao: z.coerce.number().nullish(),
  dtEncerramento: z.coerce.number().nullish(),
  sitPrograma: z.string().nullish(),
  vlrBaseIndividual: z.coerce.number().nullish(),
  vlrBaseFamiliar: z.coerce.number().nullish(),
  vlrTetoBenef: z.coerce.number().nullish(),
  vlrPisoBenef: z.coerce.number().nullish(),
  pctReajusteAnual: z.coerce.number().nullish(),
  dtUltReajuste: z.coerce.number().nullish(),
  fatorK: z.coerce.number().nullish(),
  rendaMaxPercap: z.coerce.number().nullish(),
  idadeMin: z.coerce.number().nullish(),
  idadeMax: z.coerce.number().nullish(),
  indExigeFilhos: z.string().nullish(),
  qtdMinFilhos: z.coerce.number().nullish(),
  indExigeEscola: z.string().nullish(),
  indExigeVacina: z.string().nullish(),
  indExigePrenatal: z.string().nullish(),
  indExigeBiometria: z.string().nullish(),
  dtInclusao: z.coerce.number().nullish(),
  usrInclusao: z.string().nullish(),
  dtUltAlteracao: z.coerce.number().nullish(),
  usrUltAlteracao: z.string().nullish(),
});

export type ProgramaSocialInput = z.infer<typeof programaSocialSchema>;
