import { z } from "zod";

// Validation schema for QueryCustDlg — generated by RNC from the UIR.
export const queryCustDlgSchema = z.object({
});

export type QueryCustDlgInput = z.infer<typeof queryCustDlgSchema>;
