import { z } from "zod";

// Validation schema for SearchDlg — generated by RNC from the UIR.
export const searchDlgSchema = z.object({
});

export type SearchDlgInput = z.infer<typeof searchDlgSchema>;
