import { z } from "zod";

// Validation schema for TipoFuncionario — generated by RNC from the UIR.
export const tipoFuncionarioSchema = z.object({
  tipo: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  categoriaSiarhes: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  militar: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  ignorarImportacao: z.preprocess((v) => (typeof v === "boolean" ? (v ? "S" : "N") : v), z.string().min(1)),
  dataUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.date().default(() => new Date())),
  usuarioUltAlteracao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.string().min(1).default("app")),
  versao: z.preprocess((v) => (v === "" || v == null ? undefined : v), z.coerce.number().int().default(1)),
});

export type TipoFuncionarioInput = z.infer<typeof tipoFuncionarioSchema>;
