import { z } from "zod";

// Validation schema for TipoFuncionario — generated by RNC from the UIR.
export const tipoFuncionarioSchema = z.object({
  id: z.coerce.number().int(),
  tipo: z.string().min(1),
  categoriaSiarhes: z.string().min(1),
  militar: z.string().min(1),
  ignorarImportacao: z.string().min(1),
  dataUltAlteracao: z.coerce.date(),
  usuarioUltAlteracao: z.string().min(1),
  versao: z.coerce.number().int(),
  categoriaSiarhes: z.string().min(1),
  ignorarImportacao: z.string().min(1),
});

export type TipoFuncionarioInput = z.infer<typeof tipoFuncionarioSchema>;
