import { z } from "zod";

// Validation schema for Vendors — generated by RNC from the UIR.
export const vendorsSchema = z.object({
  vendorNo: z.coerce.number().int(),
  vendorName: z.string().min(1),
  contactEmail: z.string().nullish(),
  activeStatus: z.coerce.boolean().nullish(),
});

export type VendorsInput = z.infer<typeof vendorsSchema>;
