import { z } from "zod";

// Validation schema for Vendors — generated by RNC from the UIR.
export const vendorsSchema = z.object({
  vendorno: z.coerce.number().int(),
  vendorname: z.string().min(1),
  contactemail: z.string().nullish(),
});

export type VendorsInput = z.infer<typeof vendorsSchema>;
