import { z } from "zod";

// Validation schema for Withdraw — generated by RNC from the UIR.
export const withdrawSchema = z.object({
  withdrawBalance: z.coerce.number().nullish(),
  newTotalBalance: z.coerce.number().nullish(),
  balanceBeforeWithdraw: z.coerce.number().nullish(),
  transactionId: z.string().nullish(),
  macId: z.string().nullish(),
  accountNo: z.string().nullish(),
  withdrawTime: z.coerce.date().nullish(),
  withdrawDate: z.coerce.date().nullish(),
});

export type WithdrawInput = z.infer<typeof withdrawSchema>;
