"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { ComboboxCreate } from "@/components/ui/combobox-create";
import { partsSchema, type PartsInput } from "@/lib/validation/parts";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Lookup field → options fetched live from the referenced entity's API.
function RelationSelect({ route, optionLabel, value, onChange }: {
  route: string; optionLabel: string; value: string; onChange: (v: string) => void;
}) {
  const { data } = useSWR(`/api/${route}?page=1&limit=100`, fetcher);
  const rows: any[] = data?.data ?? [];
  function label(row: any): string {
    if (row[optionLabel] != null && row[optionLabel] !== "") return String(row[optionLabel]);
    for (const [k, v] of Object.entries(row)) {
      if (k === "id" || k.endsWith("Id") || k.endsWith("_id")) continue;
      if (typeof v === "string" && v !== "") return v;
    }
    return String(row.id);
  }
  return (
    <Select value={value ?? ""} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Select…" /></SelectTrigger>
      <SelectContent>
        {rows.map((row) => (
          <SelectItem key={row.id} value={String(row.id)}>{label(row)}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// Ed Parts — edit view, generated by RNC from the UIR.
export default function PartsEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/parts/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<PartsInput>({ resolver: zodResolver(partsSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: PartsInput) {
    const res = await fetch(`/api/parts/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/parts");
  }

  async function onDelete() {
    const res = await fetch(`/api/parts/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/parts");
  }

  return (
    <div className="w-full px-6 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/parts"><ArrowLeft className="h-4 w-4" /> Back to Parts</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Ed Parts</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="onhand" className="text-sm font-medium">On Hand</label>
                <Input id="onhand" type="text" placeholder="Enter on hand" {...register("onhand")} />
                {errors.onhand && <p className="text-sm text-destructive">{String(errors.onhand?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="onorder" className="text-sm font-medium">On Order</label>
                <Input id="onorder" type="text" placeholder="Enter on order" {...register("onorder")} />
                {errors.onorder && <p className="text-sm text-destructive">{String(errors.onorder?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="cost" className="text-sm font-medium">Cost</label>
                <div className="relative">
                  <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                  <Input id="cost" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("cost", { valueAsNumber: true })} />
                </div>
                {errors.cost && <p className="text-sm text-destructive">{String(errors.cost?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="listprice" className="text-sm font-medium">List Price</label>
                <div className="relative">
                  <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                  <Input id="listprice" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("listprice", { valueAsNumber: true })} />
                </div>
                {errors.listprice && <p className="text-sm text-destructive">{String(errors.listprice?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="partno" className="text-sm font-medium">Part No</label>
                <Input id="partno" type="text" placeholder="Enter part no" {...register("partno")} />
                {errors.partno && <p className="text-sm text-destructive">{String(errors.partno?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="vendorno" className="text-sm font-medium">Vendor No</label>
                <Controller
                  control={control}
                  name={"vendorno" as never}
                  render={({ field }) => (
                    <ComboboxCreate
                      name="vendorno"
                      route="vendors"
                      optionLabel="vendorName"
                      createFields={[{"name":"vendorName","label":"Vendor Name","inputType":"text","required":true},{"name":"contactEmail","label":"Contact Email","inputType":"text","required":false},{"name":"activeStatus","label":"Active Status","inputType":"text","required":false}]}
                      value={(field.value as string) ?? ""}
                      onChange={field.onChange}
                    />
                  )}
                />
                {errors.vendorno && <p className="text-sm text-destructive">{String(errors.vendorno?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="description" className="text-sm font-medium">Description</label>
                <Textarea id="description" placeholder="Enter description" {...register("description")} />
                {errors.description && <p className="text-sm text-destructive">{String(errors.description?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
