"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { partsSchema, type PartsInput } from "@/lib/validation/parts";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Lookup field → options fetched live from the referenced entity's API.
function RelationSelect({ route, optionLabel, value, onChange }: {
  route: string; optionLabel: string; value: string; onChange: (v: string) => void;
}) {
  const { data } = useSWR(`/api/${route}?page=1&limit=100`, fetcher);
  const rows: any[] = data?.data ?? [];
  return (
    <Select value={value ?? ""} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Select…" /></SelectTrigger>
      <SelectContent>
        {rows.map((row) => (
          <SelectItem key={row.id} value={String(row.id)}>{String(row[optionLabel] ?? row.id)}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// Ed Parts — edit view, generated by RNC from the UIR.
export default function PartsEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/parts/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<PartsInput>({ resolver: zodResolver(partsSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: PartsInput) {
    const res = await fetch(`/api/parts/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/parts");
  }

  async function onDelete() {
    const res = await fetch(`/api/parts/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/parts");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/parts"><ArrowLeft className="h-4 w-4" /> Back to Parts</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Ed Parts</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="partNo" className="text-sm font-medium">Part Number</label>
                <Input id="partNo" type="text" placeholder="Enter part number" {...register("partNo")} />
                {errors.partNo && <p className="text-sm text-destructive">{String(errors.partNo?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="vendorNo" className="text-sm font-medium">Vendor Number</label>
                <Controller
                  control={control}
                  name={"vendorNo" as never}
                  render={({ field }) => (
                    <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                      <SelectTrigger id="vendorNo"><SelectValue placeholder="Select…" /></SelectTrigger>
                      <SelectContent>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.vendorNo && <p className="text-sm text-destructive">{String(errors.vendorNo?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="onHand" className="text-sm font-medium">On Hand</label>
                <Input id="onHand" type="text" placeholder="Enter on hand" {...register("onHand")} />
                {errors.onHand && <p className="text-sm text-destructive">{String(errors.onHand?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="onOrder" className="text-sm font-medium">On Order</label>
                <Input id="onOrder" type="text" placeholder="Enter on order" {...register("onOrder")} />
                {errors.onOrder && <p className="text-sm text-destructive">{String(errors.onOrder?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="cost" className="text-sm font-medium">Cost</label>
                <Input id="cost" type="text" placeholder="Enter cost" {...register("cost")} />
                {errors.cost && <p className="text-sm text-destructive">{String(errors.cost?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="listPrice" className="text-sm font-medium">List Price</label>
                <Input id="listPrice" type="text" placeholder="Enter list price" {...register("listPrice")} />
                {errors.listPrice && <p className="text-sm text-destructive">{String(errors.listPrice?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="backOrd" className="text-sm font-medium">Back Order</label>
                <Input id="backOrd" type="text" placeholder="Enter back order" {...register("backOrd")} />
                {errors.backOrd && <p className="text-sm text-destructive">{String(errors.backOrd?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="description" className="text-sm font-medium">Description</label>
                <Textarea id="description" placeholder="Enter description" {...register("description")} />
                {errors.description && <p className="text-sm text-destructive">{String(errors.description?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
