// Generated by RNC — edit locale/currency/masks in Application Settings and re-generate.
export const APP_CONFIG = {
  locale: "pt-BR",
  dateFormat: "dd/MM/yyyy",
  currencySymbol: "R$",
  useViaCep: false,
  useBrazilianGeo: false,
  customMasks: [
  ],
} as const;

export type AppConfig = typeof APP_CONFIG;
