// Default grid columns — generated by RNC from the UIR. Seeds which fields start
// visible in the table; full field config (order + form/grid visibility) lives in
// lib/ui-settings.ts. Edit via /settings.
type GridColDefault = { key: string; defaultLabel: string; label: string; visible: boolean; order: number; format?: "currency" | "date" | "boolean" };

export const ENTITY_COLS: Record<string, GridColDefault[]> = {
  habilitacaos: [
    { key: "descHabilitacao", defaultLabel: "Desc Habilitacao", label: "Desc Habilitacao", visible: true, order: 0 },
    { key: "tipoHabilitacao", defaultLabel: "Tipo Habilitacao", label: "Tipo Habilitacao", visible: true, order: 1 },
  ],
  funcionarios: [
    { key: "nome", defaultLabel: "Nome", label: "Nome", visible: true, order: 0 },
    { key: "nomeGuerra", defaultLabel: "Nome Guerra", label: "Nome Guerra", visible: true, order: 1 },
    { key: "numeroFuncional", defaultLabel: "Numero Funcional", label: "Numero Funcional", visible: true, order: 2 },
    { key: "cpf", defaultLabel: "Cpf", label: "Cpf", visible: true, order: 3 },
  ],
  auditoria_detalhada_funcionarios: [
    { key: "tabela", defaultLabel: "Tabela", label: "Tabela", visible: true, order: 0 },
    { key: "nfFuncionario", defaultLabel: "Nf Funcionario", label: "Nf Funcionario", visible: true, order: 1 },
    { key: "usuarioUltAlteracao", defaultLabel: "Usuario Ult Alteracao", label: "Usuario Ult Alteracao", visible: true, order: 2 },
    { key: "data", defaultLabel: "Data", label: "Data", visible: true, order: 3, format: "date" as const },
    { key: "evento", defaultLabel: "Evento", label: "Evento", visible: true, order: 4 },
  ],
  posto_graduacaos: [
    { key: "descricao", defaultLabel: "Descricao", label: "Descricao", visible: true, order: 0 },
    { key: "numeroOrdem", defaultLabel: "Numero Ordem", label: "Numero Ordem", visible: true, order: 1 },
    { key: "codigoSiarhes", defaultLabel: "Codigo Siarhes", label: "Codigo Siarhes", visible: true, order: 2 },
    { key: "abreviacao", defaultLabel: "Abreviacao", label: "Abreviacao", visible: true, order: 3 },
    { key: "postoGradUnificado", defaultLabel: "Posto Grad Unificado", label: "Posto Grad Unificado", visible: true, order: 4 },
  ],
  funcao_qdis: [
    { key: "nomeFuncao", defaultLabel: "Nome Funcao", label: "Nome Funcao", visible: true, order: 0 },
    { key: "nomeFuncaoSiarhes", defaultLabel: "Nome Funcao Siarhes", label: "Nome Funcao Siarhes", visible: true, order: 1 },
    { key: "ativo", defaultLabel: "Ativo", label: "Ativo", visible: true, order: 2, format: "boolean" as const },
    { key: "geral", defaultLabel: "Geral", label: "Geral", visible: true, order: 3, format: "boolean" as const },
    { key: "gratificada", defaultLabel: "Gratificada", label: "Gratificada", visible: true, order: 4, format: "boolean" as const },
  ],
  tipo_funcionarios: [
    { key: "tipo", defaultLabel: "Tipo", label: "Tipo", visible: true, order: 0 },
    { key: "categoriaSiarhes", defaultLabel: "Categoria Siarhes", label: "Categoria Siarhes", visible: true, order: 1 },
    { key: "militar", defaultLabel: "Militar", label: "Militar", visible: true, order: 2 },
    { key: "ignorarImportacao", defaultLabel: "Ignorar Importacao", label: "Ignorar Importacao", visible: true, order: 3 },
    { key: "usuarioUltAlteracao", defaultLabel: "Usuario Ult Alteracao", label: "Usuario Ult Alteracao", visible: true, order: 4 },
  ],
  atribuicaos: [
    { key: "usuarioUltAlteracao", defaultLabel: "Usuario Ult Alteracao", label: "Usuario Ult Alteracao", visible: true, order: 0 },
    { key: "avocar", defaultLabel: "Avocar", label: "Avocar", visible: true, order: 1 },
    { key: "avocar2", defaultLabel: "Avocar2", label: "Avocar2", visible: true, order: 2 },
    { key: "avocar3", defaultLabel: "Avocar3", label: "Avocar3", visible: true, order: 3 },
    { key: "delegar", defaultLabel: "Delegar", label: "Delegar", visible: true, order: 4 },
  ],
};

export const ENTITY_LABELS: Record<string, string> = {
  habilitacaos: "Habilitacaos",
  funcionarios: "Funcionarios",
  auditoria_detalhada_funcionarios: "Auditoria Detalhada Funcionarios",
  posto_graduacaos: "Posto Graduacaos",
  funcao_qdis: "Funcao Qdis",
  tipo_funcionarios: "Tipo Funcionarios",
  atribuicaos: "Atribuicaos",
};
