// Default grid columns — generated by RNC from the UIR. Seeds which fields start
// visible in the table; full field config (order + form/grid visibility) lives in
// lib/ui-settings.ts. Edit via /settings.
type GridColDefault = { key: string; defaultLabel: string; label: string; visible: boolean; order: number; format?: "currency" | "date" | "boolean" };

export const ENTITY_COLS: Record<string, GridColDefault[]> = {
  auditorias: [
    { key: "nomeUsuario", defaultLabel: "Nome Usuario", label: "Nome Usuario", visible: true, order: 0 },
    { key: "numAuditoria", defaultLabel: "Num Auditoria", label: "Num Auditoria", visible: true, order: 1 },
    { key: "dtEvento", defaultLabel: "Dt Evento", label: "Dt Evento", visible: true, order: 2 },
    { key: "hrEvento", defaultLabel: "Hr Evento", label: "Hr Evento", visible: true, order: 3 },
    { key: "tsEvento", defaultLabel: "Ts Evento", label: "Ts Evento", visible: true, order: 4 },
  ],
  pagamentos: [
    { key: "anoMesRef", defaultLabel: "Ano Mes Ref", label: "Ano Mes Ref", visible: true, order: 0 },
    { key: "vlrDescontoTotal", defaultLabel: "Vlr Desconto Total", label: "Vlr Desconto Total", visible: true, order: 1 },
    { key: "numPagamento", defaultLabel: "Num Pagamento", label: "Num Pagamento", visible: true, order: 2 },
    { key: "numCpf", defaultLabel: "Num Cpf", label: "Num Cpf", visible: true, order: 3 },
    { key: "numInscricao", defaultLabel: "Num Inscricao", label: "Num Inscricao", visible: true, order: 4 },
  ],
  pagamento_grp_descontos: [
    { key: "tipoDesconto", defaultLabel: "Tipo Desconto", label: "Tipo Desconto", visible: true, order: 0 },
    { key: "vlrDesconto", defaultLabel: "Vlr Desconto", label: "Vlr Desconto", visible: true, order: 1 },
    { key: "pctDesconto", defaultLabel: "Pct Desconto", label: "Pct Desconto", visible: true, order: 2 },
    { key: "numProcesso", defaultLabel: "Num Processo", label: "Num Processo", visible: true, order: 3 },
    { key: "dtInicioDsct", defaultLabel: "Dt Inicio Dsct", label: "Dt Inicio Dsct", visible: true, order: 4 },
  ],
  programa_socials: [
    { key: "nomePrograma", defaultLabel: "Nome Programa", label: "Nome Programa", visible: true, order: 0 },
    { key: "codPrograma", defaultLabel: "Cod Programa", label: "Cod Programa", visible: true, order: 1 },
    { key: "siglaPrograma", defaultLabel: "Sigla Programa", label: "Sigla Programa", visible: true, order: 2 },
    { key: "tipoPrograma", defaultLabel: "Tipo Programa", label: "Tipo Programa", visible: true, order: 3 },
    { key: "orgaoResponsavel", defaultLabel: "Orgao Responsavel", label: "Orgao Responsavel", visible: true, order: 4 },
  ],
  programa_social_grp_faixa_calculos: [
    { key: "rendaInicio", defaultLabel: "Renda Inicio", label: "Renda Inicio", visible: true, order: 0 },
    { key: "rendaFim", defaultLabel: "Renda Fim", label: "Renda Fim", visible: true, order: 1 },
    { key: "fatorMultiplicador", defaultLabel: "Fator Multiplicador", label: "Fator Multiplicador", visible: true, order: 2 },
    { key: "vlrAdicional", defaultLabel: "Vlr Adicional", label: "Vlr Adicional", visible: true, order: 3 },
    { key: "indAcumulativo", defaultLabel: "Ind Acumulativo", label: "Ind Acumulativo", visible: true, order: 4 },
  ],
  programa_social_grp_param_regionals: [
    { key: "codRegiao", defaultLabel: "Cod Regiao", label: "Cod Regiao", visible: true, order: 0 },
    { key: "fatorRegional", defaultLabel: "Fator Regional", label: "Fator Regional", visible: true, order: 1 },
    { key: "vlrComplementoReg", defaultLabel: "Vlr Complemento Reg", label: "Vlr Complemento Reg", visible: true, order: 2 },
    { key: "indAtivoRegiao", defaultLabel: "Ind Ativo Regiao", label: "Ind Ativo Regiao", visible: true, order: 3 },
    { key: "occurrence", defaultLabel: "Occurrence", label: "Occurrence", visible: true, order: 4 },
  ],
  beneficiarios: [
    { key: "nomeCompleto", defaultLabel: "Nome Completo", label: "Nome Completo", visible: true, order: 0 },
    { key: "nomeMae", defaultLabel: "Nome Mae", label: "Nome Mae", visible: true, order: 1 },
    { key: "nomePai", defaultLabel: "Nome Pai", label: "Nome Pai", visible: true, order: 2 },
    { key: "rgNumero", defaultLabel: "Rg Numero", label: "Rg Numero", visible: true, order: 3 },
    { key: "numero", defaultLabel: "Numero", label: "Numero", visible: true, order: 4 },
  ],
  beneficiario_grp_dependentes: [
    { key: "nomeDependente", defaultLabel: "Nome Dependente", label: "Nome Dependente", visible: true, order: 0 },
    { key: "cpfDependente", defaultLabel: "Cpf Dependente", label: "Cpf Dependente", visible: true, order: 1 },
    { key: "dtNascDepend", defaultLabel: "Dt Nasc Depend", label: "Dt Nasc Depend", visible: true, order: 2 },
    { key: "parentesco", defaultLabel: "Parentesco", label: "Parentesco", visible: true, order: 3 },
    { key: "sitDependente", defaultLabel: "Sit Dependente", label: "Sit Dependente", visible: true, order: 4 },
  ],
};

export const ENTITY_LABELS: Record<string, string> = {
  auditorias: "Auditorias",
  pagamentos: "Pagamentos",
  pagamento_grp_descontos: "Pagamento Grp Descontos",
  programa_socials: "Programa Socials",
  programa_social_grp_faixa_calculos: "Programa Social Grp Faixa Calculos",
  programa_social_grp_param_regionals: "Programa Social Grp Param Regionals",
  beneficiarios: "Beneficiarios",
  beneficiario_grp_dependentes: "Beneficiario Grp Dependentes",
};
