// Full field catalog per entity — generated by RNC from the UIR.
// widget ← resolved field type; relation ← FieldReference, else FK column ownership.
import type { ColFormat } from "@/lib/ui-settings";

export type FieldWidget = "text" | "number" | "date" | "boolean" | "lookup";

export interface FieldRelation { route: string; valueField: string; labelField: string }

export interface FieldMeta { key: string; label: string; widget: FieldWidget; format?: ColFormat; relation?: FieldRelation }

export const ENTITY_FIELDS: Record<string, FieldMeta[]> = {
  funcionarios: [
    { key: "nome", label: "Nome", widget: "text" },
    { key: "nomeGuerra", label: "Nome Guerra", widget: "text" },
    { key: "numeroFuncional", label: "Numero Funcional", widget: "text" },
    { key: "cpf", label: "Cpf", widget: "text" },
  ],
  auditoria_detalhada_funcionarios: [
    { key: "tabela", label: "Tabela", widget: "text" },
    { key: "nfFuncionario", label: "Nf Funcionario", widget: "text" },
    { key: "usuarioUltAlteracao", label: "Usuario Ult Alteracao", widget: "text" },
    { key: "data", label: "Data", widget: "date", format: "date" as const },
    { key: "evento", label: "Evento", widget: "text" },
    { key: "observacao", label: "Observacao", widget: "text" },
  ],
  funcao_qdis: [
    { key: "nomeFuncao", label: "Nome Funcao", widget: "text" },
    { key: "nomeFuncaoSiarhes", label: "Nome Funcao Siarhes", widget: "text" },
    { key: "ativo", label: "Ativo", widget: "boolean", format: "boolean" as const },
    { key: "geral", label: "Geral", widget: "boolean", format: "boolean" as const },
    { key: "gratificada", label: "Gratificada", widget: "boolean", format: "boolean" as const },
  ],
  tipo_funcionarios: [
    { key: "tipo", label: "Tipo", widget: "text" },
    { key: "categoriaSiarhes", label: "Categoria Siarhes", widget: "text" },
    { key: "militar", label: "Militar", widget: "text" },
    { key: "ignorarImportacao", label: "Ignorar Importacao", widget: "text" },
    { key: "usuarioUltAlteracao", label: "Usuario Ult Alteracao", widget: "text" },
    { key: "categoriaSiarhes", label: "Categoria Siarhes", widget: "text" },
    { key: "ignorarImportacao", label: "Ignorar Importacao", widget: "text" },
    { key: "dataUltAlteracao", label: "Data Ult Alteracao", widget: "date", format: "date" as const },
    { key: "id", label: "Id", widget: "number" },
    { key: "versao", label: "Versao", widget: "number" },
  ],
};
