// Full field catalog per entity — generated by RNC from the UIR.
// widget ← resolved field type; relation ← FieldReference, else FK column ownership.
import type { ColFormat } from "@/lib/ui-settings";

export type FieldWidget = "text" | "number" | "date" | "boolean" | "lookup";

export interface FieldRelation { route: string; valueField: string; labelField: string }

export interface FieldMeta { key: string; label: string; widget: FieldWidget; format?: ColFormat; relation?: FieldRelation }

export const ENTITY_FIELDS: Record<string, FieldMeta[]> = {
  nccruises: [
    { key: "cruiseId", label: "Cruise Id", widget: "number" },
    { key: "cruiseStatus", label: "Cruise Status", widget: "text" },
    { key: "startDate", label: "Start Date", widget: "text" },
    { key: "startTime", label: "Start Time", widget: "number" },
    { key: "endDate", label: "End Date", widget: "number" },
    { key: "endTime", label: "End Time", widget: "number" },
    { key: "startHarbor", label: "Start Harbor", widget: "text" },
    { key: "destinationHarbor", label: "Destination Harbor", widget: "text" },
    { key: "idYacht", label: "Id Yacht", widget: "number" },
    { key: "price1W", label: "Price 1 W", widget: "number", format: "currency" as const },
    { key: "price2W", label: "Price 2 W", widget: "number", format: "currency" as const },
    { key: "price3W", label: "Price 3 W", widget: "number", format: "currency" as const },
  ],
  ncyachts: [
    { key: "yachtName", label: "Yacht Name", widget: "text" },
    { key: "yachtId", label: "Yacht Id", widget: "number" },
    { key: "yachtType", label: "Yacht Type", widget: "text" },
    { key: "length", label: "Length", widget: "number", format: "currency" as const },
    { key: "width", label: "Width", widget: "number", format: "currency" as const },
    { key: "draft", label: "Draft", widget: "number", format: "currency" as const },
    { key: "sailSurface", label: "Sail Surface", widget: "number", format: "currency" as const },
    { key: "motor", label: "Motor", widget: "number", format: "currency" as const },
    { key: "headRoom", label: "Head Room", widget: "number", format: "currency" as const },
    { key: "bunks", label: "Bunks", widget: "number", format: "currency" as const },
  ],
};
