// Full field catalog per entity — generated by RNC from the UIR.
// widget ← resolved field type; relation ← FieldReference, else FK column ownership.
import type { ColFormat } from "@/lib/ui-settings";

export type FieldWidget = "text" | "number" | "date" | "boolean" | "lookup";

export interface FieldRelation { route: string; valueField: string; labelField: string }

export interface FieldMeta { key: string; label: string; widget: FieldWidget; format?: ColFormat; relation?: FieldRelation }

export const ENTITY_FIELDS: Record<string, FieldMeta[]> = {
  parts: [
    { key: "onhand", label: "On Hand", widget: "text" },
    { key: "onorder", label: "On Order", widget: "text" },
    { key: "cost", label: "Cost", widget: "number", format: "currency" as const },
    { key: "listprice", label: "List Price", widget: "number", format: "currency" as const },
    { key: "partno", label: "Part No", widget: "text" },
    { key: "vendorno", label: "Vendor No", widget: "text" },
    { key: "description", label: "Description", widget: "text" },
  ],
  customers: [
    { key: "company", label: "Company", widget: "text" },
    { key: "addr1", label: "Addr1", widget: "text" },
    { key: "addr2", label: "Addr2", widget: "text" },
    { key: "city", label: "City", widget: "text" },
    { key: "state", label: "State", widget: "text" },
    { key: "zip", label: "Zip", widget: "text" },
    { key: "country", label: "Country", widget: "text" },
    { key: "phone", label: "Phone", widget: "text" },
    { key: "taxrate", label: "Tax Rate", widget: "text" },
    { key: "contact", label: "Contact", widget: "text" },
    { key: "lastinvoicedate", label: "Last Invoice Date", widget: "date", format: "date" as const },
    { key: "fax", label: "Fax", widget: "text" },
    { key: "custno", label: "Cust No", widget: "text" },
  ],
  orders: [
    { key: "shiptoaddr1", label: "Ship To Addr1", widget: "text" },
    { key: "shiptoaddr2", label: "Ship To Addr2", widget: "text" },
    { key: "shiptocontact", label: "Ship To Contact", widget: "text" },
    { key: "shiptocity", label: "Ship To City", widget: "text" },
    { key: "shiptostate", label: "Ship To State", widget: "text" },
    { key: "shiptozip", label: "Ship To Zip", widget: "text" },
    { key: "po", label: "Po", widget: "text" },
    { key: "terms", label: "Terms", widget: "text" },
    { key: "paymentmethod", label: "Payment Method", widget: "text" },
    { key: "shipvia", label: "Ship Via", widget: "text" },
    { key: "saledate", label: "Sale Date", widget: "date", format: "date" as const },
    { key: "amountpaid", label: "Amount Paid", widget: "number", format: "currency" as const },
    { key: "freight", label: "Freight", widget: "number", format: "currency" as const },
    { key: "amountdue", label: "Amount Due", widget: "number", format: "currency" as const },
    { key: "taxrate", label: "Tax Rate", widget: "text" },
    { key: "empno", label: "Emp No", widget: "lookup", relation: { route: "employees", valueField: "empno", labelField: "fullname" } },
    { key: "custno", label: "Cust No", widget: "lookup", relation: { route: "customers", valueField: "custno", labelField: "company" } },
    { key: "addr1", label: "Addr1", widget: "text" },
    { key: "addr2", label: "Addr2", widget: "text" },
    { key: "city", label: "City", widget: "text" },
    { key: "state", label: "State", widget: "text" },
    { key: "zip", label: "Zip", widget: "text" },
    { key: "itemstotal", label: "Items Total", widget: "text" },
    { key: "taxtotal", label: "Tax Total", widget: "text" },
    { key: "orderno", label: "Order No", widget: "text" },
  ],
  vendors: [
    { key: "vendorName", label: "Vendor Name", widget: "text" },
    { key: "contactEmail", label: "Contact Email", widget: "text" },
    { key: "activeStatus", label: "Active Status", widget: "text" },
  ],
  items: [
    { key: "description", label: "Description", widget: "text" },
    { key: "itemno", label: "Itemno", widget: "text" },
    { key: "orderno", label: "Orderno", widget: "lookup", relation: { route: "orders", valueField: "orderno", labelField: "custno" } },
    { key: "sellprice", label: "Sellprice", widget: "text" },
    { key: "qty", label: "Qty", widget: "text" },
    { key: "discount", label: "Discount", widget: "text" },
    { key: "extprice", label: "Extprice", widget: "text" },
    { key: "partno", label: "Partno", widget: "lookup", relation: { route: "parts", valueField: "partno", labelField: "description" } },
  ],
  employees: [
    { key: "fullname", label: "Fullname", widget: "text" },
    { key: "lastname", label: "Lastname", widget: "text" },
    { key: "firstname", label: "Firstname", widget: "text" },
    { key: "empno", label: "Empno", widget: "text" },
    { key: "phoneext", label: "Phoneext", widget: "text" },
    { key: "hiredate", label: "Hiredate", widget: "date", format: "date" as const },
    { key: "salary", label: "Salary", widget: "text" },
  ],
};
