// Sidebar navigation — generated by RNC from the UIR.
export interface NavItem { label: string; href: string }

export const appName = "RNC App";

export const navItems: NavItem[] = [
  { label: "Nccruises", href: "/nccruises" },
];
