// Sidebar navigation — generated by RNC from the UIR.
// `icon` is a statically-imported Lucide component (no lucide-react/dynamic) so only
// the icons actually used are bundled — keeps dev compile fast.
import { Briefcase, Building2, Calendar, GraduationCap, Table, type LucideIcon } from 'lucide-react';

export interface NavItem { label: string; href: string; icon: LucideIcon }

export const appName = "Modernized App";

export const navItems: NavItem[] = [
  { label: "Cursos", href: "/cursos", icon: GraduationCap },
  { label: "Funcionarios", href: "/funcionarios", icon: Briefcase },
  { label: "Lotacaos", href: "/lotacaos", icon: Building2 },
  { label: "Mes Ano Ferias", href: "/mes_ano_ferias", icon: Calendar },
];
