// Sidebar navigation — generated by RNC from the UIR.
// `icon` is a statically-imported Lucide component (no lucide-react/dynamic) so only
// the icons actually used are bundled — keeps dev compile fast.
import { Briefcase, ShoppingCart, Table, Users, type LucideIcon } from 'lucide-react';

export interface NavItem { label: string; href: string; icon: LucideIcon }

export const appName = "Rodney APP";

export const navItems: NavItem[] = [
  { label: "Customers", href: "/customers", icon: Users },
  { label: "Orders", href: "/orders", icon: ShoppingCart },
  { label: "Employees", href: "/employees", icon: Briefcase },
];
