// lib/types.ts — shared TypeScript types, generated by RNC from the UIR contract.
// Single import point for all entity input types; keeps pages decoupled from validation schema paths.
// Generated by RNC — do not edit manually.

export type { FuncionarioInput } from "@/lib/validation/funcionario";
export type { TipoFuncionarioInput } from "@/lib/validation/tipoFuncionario";
export type { AuditoriaDetalhadaFuncionarioInput } from "@/lib/validation/auditoriaDetalhadaFuncionario";
export type { FuncaoQdiInput } from "@/lib/validation/funcaoQdi";
