// lib/types.ts — shared TypeScript types, generated by RNC from the UIR contract.
// Single import point for all entity input types; keeps pages decoupled from validation schema paths.
// Generated by RNC — do not edit manually.

export type { NccruiseInput } from "@/lib/validation/nccruise";
export type { NcyachtInput } from "@/lib/validation/ncyacht";
