// lib/types.ts — shared TypeScript types, generated by RNC from the UIR contract.
// Single import point for all entity input types; keeps pages decoupled from validation schema paths.
// Generated by RNC — do not edit manually.

export type { CursoInput } from "@/lib/validation/curso";
export type { FuncionarioInput } from "@/lib/validation/funcionario";
export type { LotacaoInput } from "@/lib/validation/lotacao";
export type { MesAnoFeriasInput } from "@/lib/validation/mesAnoFerias";
