"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { queryCustDlgSchema, type QueryCustDlgInput } from "@/lib/validation/queryCustDlg";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Query Cust Dlg — edit view, generated by RNC from the UIR.
export default function QueryCustDlgEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/query_cust_dlgs/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<QueryCustDlgInput>({ resolver: zodResolver(queryCustDlgSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: QueryCustDlgInput) {
    const res = await fetch(`/api/query_cust_dlgs/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/query_cust_dlgs");
  }

  async function onDelete() {
    const res = await fetch(`/api/query_cust_dlgs/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/query_cust_dlgs");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/query_cust_dlgs"><ArrowLeft className="h-4 w-4" /> Back to Query Cust Dlgs</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Query Cust Dlg</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="field1" className="text-sm font-medium">Field 1</label>
                <Input id="field1" type="text" placeholder="Enter field 1" {...register("field1")} />
                {errors.field1 && <p className="text-sm text-destructive">{String(errors.field1?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="field2" className="text-sm font-medium">Field 2</label>
                <Input id="field2" type="text" placeholder="Enter field 2" {...register("field2")} />
                {errors.field2 && <p className="text-sm text-destructive">{String(errors.field2?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
