"use client";
import useSWR from "swr";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Withdraws — list view, generated by RNC from the UIR.
export default function WithdrawsPage() {
  const { data, isLoading } = useSWR(`/api/withdraws?page=1&limit=20`, fetcher);
  const rows = data?.data ?? [];

  return (
    <div className="container mx-auto py-8">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold">Withdraws</h1>
        <Button asChild><Link href="/withdraws/new">New Withdraw Balance Yt Bank Of India</Link></Button>
      </div>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b text-left">
            <th className="py-2 pr-4">balancebeforewithdraw</th>
            <th className="py-2 pr-4">withdrawballance</th>
            <th className="py-2 pr-4">newtotalballance</th>
            <th className="py-2 pr-4">fillbalancebeforewithdraw</th>
            <th className="py-2 pr-4">TotalBalancecustomer</th>
            <th className="py-2 pr-4">transactionid</th>
            <th className="py-2 pr-4">macid</th>
            <th className="py-2 pr-4">accountno</th>
            <th className="py-2 pr-4">newaccountno</th>
            <th className="py-2 pr-4">LabelTime</th>
            <th className="py-2 pr-4">datecap</th>
            <th className="py-2 pr-4">Label1</th>
            <th className="py-2"></th>
          </tr>
        </thead>
        <tbody>
          {isLoading && (<tr><td className="py-4 text-muted-foreground">Loading…</td></tr>)}
          {rows.map((row: any) => (
            <tr key={row.id} className="border-b">
              <td className="py-2 pr-4">{String(row.accountBallance ?? "")}</td>
              <td className="py-2 pr-4">{String(row.withdrawBalance ?? "")}</td>
              <td className="py-2 pr-4">{String(row.newTotalBalance ?? "")}</td>
              <td className="py-2 pr-4">{String(row.balanceBeforeWithdraw ?? "")}</td>
              <td className="py-2 pr-4">{String(row.accountBallance ?? "")}</td>
              <td className="py-2 pr-4">{String(row.transactionId ?? "")}</td>
              <td className="py-2 pr-4">{String(row.macId ?? "")}</td>
              <td className="py-2 pr-4">{String(row.accountNo ?? "")}</td>
              <td className="py-2 pr-4">{String(row.accountNo ?? "")}</td>
              <td className="py-2 pr-4">{String(row.withdrawTime ?? "")}</td>
              <td className="py-2 pr-4">{String(row.withdrawDate ?? "")}</td>
              <td className="py-2 pr-4">{String(row.accountNo ?? "")}</td>
              <td className="py-2">
                <Button variant="ghost" size="sm" asChild>
                  <Link href={`/withdraws/${row.id}/edit`}>Edit</Link>
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
