"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { ComboboxCreate } from "@/components/ui/combobox-create";
import { employeeSchema, type EmployeeInput } from "@/lib/validation/employee";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Lookup field → options fetched live from the referenced entity's API.
function RelationSelect({ route, optionLabel, value, onChange }: {
  route: string; optionLabel: string; value: string; onChange: (v: string) => void;
}) {
  const { data } = useSWR(`/api/${route}?page=1&limit=100`, fetcher);
  const rows: any[] = data?.data ?? [];
  return (
    <Select value={value ?? ""} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Select…" /></SelectTrigger>
      <SelectContent>
        {rows.map((row) => (
          <SelectItem key={row.id} value={String(row.id)}>{String(row[optionLabel] ?? row.id)}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// Employee — edit view, generated by RNC from the UIR.
export default function EmployeeEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/employees/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<EmployeeInput>({ resolver: zodResolver(employeeSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: EmployeeInput) {
    const res = await fetch(`/api/employees/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/employees");
  }

  async function onDelete() {
    const res = await fetch(`/api/employees/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/employees");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/employees"><ArrowLeft className="h-4 w-4" /> Back to Employees</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Employee</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="fullname" className="text-sm font-medium">Fullname</label>
                <Input id="fullname" type="text" placeholder="Enter fullname" {...register("fullname")} />
                {errors.fullname && <p className="text-sm text-destructive">{String(errors.fullname?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="lastname" className="text-sm font-medium">Lastname</label>
                <Input id="lastname" type="text" placeholder="Enter lastname" {...register("lastname")} />
                {errors.lastname && <p className="text-sm text-destructive">{String(errors.lastname?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="firstname" className="text-sm font-medium">Firstname</label>
                <Input id="firstname" type="text" placeholder="Enter firstname" {...register("firstname")} />
                {errors.firstname && <p className="text-sm text-destructive">{String(errors.firstname?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="empno" className="text-sm font-medium">Empno</label>
                <Input id="empno" type="text" placeholder="Enter empno" {...register("empno")} />
                {errors.empno && <p className="text-sm text-destructive">{String(errors.empno?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="phoneext" className="text-sm font-medium">Phoneext</label>
                <Input id="phoneext" type="text" placeholder="Enter phoneext" {...register("phoneext")} />
                {errors.phoneext && <p className="text-sm text-destructive">{String(errors.phoneext?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="hiredate" className="text-sm font-medium">Hiredate</label>
                <Input id="hiredate" type="date" {...register("hiredate")} />
                {errors.hiredate && <p className="text-sm text-destructive">{String(errors.hiredate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="salary" className="text-sm font-medium">Salary</label>
                <Input id="salary" type="text" placeholder="Enter salary" {...register("salary")} />
                {errors.salary && <p className="text-sm text-destructive">{String(errors.salary?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
