-- Generated by RNC — sqlite dialect
-- WARNING: tables marked INFERRED were reconstructed from screen-field
--          bindings; column types are heuristic and have no primary key.

CREATE TABLE PARTS (
    PARTNO  REAL NOT NULL,
    DESCRIPTION  TEXT NOT NULL,
    ONHAND  REAL,
    ONORDER  REAL,
    VENDORNO  REAL,
    COST  NUMERIC,
    LISTPRICE  NUMERIC,
    BACKORD  INTEGER,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE ORDERS (
    ORDERNO  REAL,
    CUSTNO  REAL NOT NULL,
    SALEDATE  TEXT,
    SHIPDATE  TEXT,
    SHIPTOCONTACT  TEXT,
    SHIPTOADDR1  TEXT,
    SHIPTOADDR2  TEXT,
    SHIPTOCITY  TEXT,
    SHIPTOSTATE  TEXT,
    SHIPTOZIP  TEXT,
    SHIPTOCOUNTRY  TEXT,
    SHIPTOPHONE  TEXT,
    SHIPVIA  TEXT,
    PO  TEXT,
    EMPNO  INTEGER NOT NULL,
    TERMS  TEXT,
    PAYMENTMETHOD  TEXT,
    ITEMSTOTAL  NUMERIC,
    TAXRATE  REAL,
    TAXTOTAL  NUMERIC,
    FREIGHT  NUMERIC,
    AMOUNTPAID  NUMERIC,
    AMOUNTDUE  NUMERIC,
    SALESPERSON  TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE CUSTOMER (
    CUSTNO  REAL,
    COMPANY  TEXT,
    ADDR1  TEXT,
    ADDR2  TEXT,
    CITY  TEXT,
    STATE  TEXT,
    ZIP  TEXT,
    COUNTRY  TEXT,
    PHONE  TEXT,
    FAX  TEXT,
    TAXRATE  REAL,
    CONTACT  TEXT,
    LASTINVOICEDATE  TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE NEXTCUST (
    NEWCUST  REAL,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE VENDORS (
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE ITEMS (
    ITEMNO  REAL,
    ORDERNO  REAL,
    DESCRIPTION  TEXT,
    SELLPRICE  NUMERIC,
    QTY  INTEGER,
    DISCOUNT  REAL,
    EXTPRICE  NUMERIC,
    PARTNO  REAL,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE NEXTORD (
    NEWKEY  REAL,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE EMPLOYEE (
    EMPNO  INTEGER,
    FULLNAME  TEXT,
    LASTNAME  TEXT,
    FIRSTNAME  TEXT,
    PHONEEXT  TEXT,
    HIREDATE  TEXT,
    SALARY  REAL,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- INFERRED table — verify against legacy DB
CREATE TABLE PICK_RPT (
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- INFERRED table — verify against legacy DB
CREATE TABLE PICK_ORDER_NO_DLG (
    DBLOOKUP_LIST_BOX1  TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- INFERRED table — verify against legacy DB
CREATE TABLE SEARCH_DLG (
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- INFERRED table — verify against legacy DB
CREATE TABLE QUERY_CUST_DLG (
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

