-- Generated by RNC — sqlite dialect
-- WARNING: tables marked INFERRED were reconstructed from screen-field
--          bindings; column types are heuristic and have no primary key.

-- INFERRED table — verify against legacy DB
CREATE TABLE ADMIN_DETAILS (
    NAME  TEXT,
    EMAIL  TEXT,
    PIN  TEXT,
    PHONENO  TEXT,
    IMAGE  TEXT,
    DOJ  TEXT,
    ID  TEXT,
    ADDRESS  TEXT,
    GENDER  TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- INFERRED table — verify against legacy DB
CREATE TABLE CUSTOMER_DETAILS (
    ACCOUNT_NO  TEXT,
    ACCOUNT_BALLANCE  NUMERIC,
    NAME  TEXT,
    DOB  TEXT,
    GVTID_NO  TEXT,
    GVTID_TYPE  TEXT,
    PHONENO  TEXT,
    IMAGE  TEXT,
    GENDER  TEXT,
    REG_DATE  TEXT,
    ADDRESS  TEXT,
    EMAIL  TEXT,
    ACCOUNT_TYPE  TEXT,
    ID  TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- INFERRED table — verify against legacy DB
CREATE TABLE DEPOSITE (
    DPOSITE_TIME  TEXT,
    ACCOUNT_NO  TEXT,
    MAC_ID  TEXT,
    TRANSACTION_ID  TEXT,
    BALLANCE_BEFORE_DEPOSITE  NUMERIC,
    NEW_TOTAL_BALLANCE  NUMERIC,
    DEPOSITE_BALLANCE  NUMERIC,
    DEPOSITE_DATE  TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- INFERRED table — verify against legacy DB
CREATE TABLE WITHDRAW (
    WITHDRAW_BALANCE  NUMERIC,
    NEW_TOTAL_BALANCE  NUMERIC,
    BALANCE_BEFORE_WITHDRAW  NUMERIC,
    TRANSACTION_ID  TEXT,
    MAC_ID  TEXT,
    ACCOUNT_NO  TEXT,
    WITHDRAW_TIME  TEXT,
    WITHDRAW_DATE  TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- INFERRED table — verify against legacy DB
CREATE TABLE NEW_CUSTOMER_REGISTRATION (
    DOB  TEXT,
    PASSWORD  TEXT,
    ADDRESS  TEXT,
    GVTID_TYPE  TEXT,
    PHONENO  TEXT,
    GENDER  TEXT,
    EMAIL  TEXT,
    ACCOUNT_TYPE  TEXT,
    GVTID_NO  TEXT,
    NAME  TEXT,
    USERNAMEE  TEXT,
    IMAGE  TEXT,
    REG_DATE  TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

