"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { forgetPasswordCustomerSchema, type ForgetPasswordCustomerInput } from "@/lib/validation/forgetPasswordCustomer";

// Forget Password Customer — create/edit form, generated by RNC from the UIR.
export default function ForgetPasswordCustomerForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<ForgetPasswordCustomerInput>({ resolver: zodResolver(forgetPasswordCustomerSchema) });

  async function onSubmit(values: ForgetPasswordCustomerInput) {
    const res = await fetch("/api/forget_password_customers", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/forget_password_customers");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Forget Password Customer</h1>
      <Button type="submit">Save</Button>
    </form>
  );
}
