"use client";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { depositeSchema, type DepositeInput } from "@/lib/validation/deposite";

// Deposite Balance Yt Bank Of India — create/edit form, generated by RNC from the UIR.
export default function DepositeForm() {
  const router = useRouter();
  const { register, handleSubmit, control, formState: { errors, isSubmitting } } =
    useForm<DepositeInput>({ resolver: zodResolver(depositeSchema) });

  async function onSubmit(values: DepositeInput) {
    const res = await fetch("/api/deposites", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/deposites");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/deposites"><ArrowLeft className="h-4 w-4" /> Back to Deposites</Link>
      </Button>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Card>
          <CardHeader>
            <CardTitle>Deposite Balance Yt Bank Of India</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <label htmlFor="dpositeTime" className="text-sm font-medium">Deposite Time</label>
              <Input id="dpositeTime" type="url" placeholder="Enter deposite time" {...register("dpositeTime")} />
              {errors.dpositeTime && <p className="text-sm text-destructive">{String(errors.dpositeTime?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="accountNo" className="text-sm font-medium">Account No</label>
              <Input id="accountNo" type="text" placeholder="Enter account no" {...register("accountNo")} />
              {errors.accountNo && <p className="text-sm text-destructive">{String(errors.accountNo?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="accountNo" className="text-sm font-medium">Account No</label>
              <Input id="accountNo" type="text" placeholder="Enter account no" {...register("accountNo")} />
              {errors.accountNo && <p className="text-sm text-destructive">{String(errors.accountNo?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="macId" className="text-sm font-medium">Mac Id</label>
              <Input id="macId" type="text" placeholder="Enter mac id" {...register("macId")} />
              {errors.macId && <p className="text-sm text-destructive">{String(errors.macId?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="transactionId" className="text-sm font-medium">Transaction Id</label>
              <Input id="transactionId" type="text" placeholder="Enter transaction id" {...register("transactionId")} />
              {errors.transactionId && <p className="text-sm text-destructive">{String(errors.transactionId?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="accountBallance" className="text-sm font-medium">Account Balance</label>
              <Input id="accountBallance" type="text" placeholder="Enter account balance" {...register("accountBallance")} />
              {errors.accountBallance && <p className="text-sm text-destructive">{String(errors.accountBallance?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="ballanceBeforeDeposite" className="text-sm font-medium">Balance Before Deposite</label>
              <Input id="ballanceBeforeDeposite" type="url" placeholder="Enter balance before deposite" {...register("ballanceBeforeDeposite")} />
              {errors.ballanceBeforeDeposite && <p className="text-sm text-destructive">{String(errors.ballanceBeforeDeposite?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="newTotalBallance" className="text-sm font-medium">New Total Balance</label>
              <Input id="newTotalBallance" type="text" placeholder="Enter new total balance" {...register("newTotalBallance")} />
              {errors.newTotalBallance && <p className="text-sm text-destructive">{String(errors.newTotalBallance?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="depositeBallance" className="text-sm font-medium">Deposite Balance</label>
              <Input id="depositeBallance" type="url" placeholder="Enter deposite balance" {...register("depositeBallance")} />
              {errors.depositeBallance && <p className="text-sm text-destructive">{String(errors.depositeBallance?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="accountBallance" className="text-sm font-medium">Account Balance</label>
              <Input id="accountBallance" type="url" placeholder="Enter account balance" {...register("accountBallance")} />
              {errors.accountBallance && <p className="text-sm text-destructive">{String(errors.accountBallance?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="depositeDate" className="text-sm font-medium">Deposite Date</label>
              <Input id="depositeDate" type="url" placeholder="Enter deposite date" {...register("depositeDate")} />
              {errors.depositeDate && <p className="text-sm text-destructive">{String(errors.depositeDate?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="accountNo" className="text-sm font-medium">Account No</label>
              <Input id="accountNo" type="text" placeholder="Enter account no" {...register("accountNo")} />
              {errors.accountNo && <p className="text-sm text-destructive">{String(errors.accountNo?.message ?? "")}</p>}
            </div>
          </CardContent>
          <CardFooter className="justify-end gap-2">
            <Button type="button" variant="outline" asChild>
              <Link href="/deposites">Cancel</Link>
            </Button>
            <Button type="submit" disabled={isSubmitting}>Save</Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  );
}
