"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { depositeSchema, type DepositeInput } from "@/lib/validation/deposite";

// Deposite Balance Yt Bank Of India — create/edit form, generated by RNC from the UIR.
export default function DepositeForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<DepositeInput>({ resolver: zodResolver(depositeSchema) });

  async function onSubmit(values: DepositeInput) {
    const res = await fetch("/api/deposites", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/deposites");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Deposite Balance Yt Bank Of India</h1>
      <div className="space-y-1">
        <label htmlFor="dpositeTime" className="text-sm font-medium">LabelTime</label>
        <Input id="dpositeTime" type="url" placeholder="Enter labeltime" {...register("dpositeTime")} />
        {errors.dpositeTime && <p className="text-sm text-red-500">{String(errors.dpositeTime?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountNo" className="text-sm font-medium">newaccountno</label>
        <Input id="accountNo" type="text" placeholder="Enter newaccountno" {...register("accountNo")} />
        {errors.accountNo && <p className="text-sm text-red-500">{String(errors.accountNo?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountNo" className="text-sm font-medium">accountno</label>
        <Input id="accountNo" type="text" placeholder="Enter accountno" {...register("accountNo")} />
        {errors.accountNo && <p className="text-sm text-red-500">{String(errors.accountNo?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="macId" className="text-sm font-medium">macid</label>
        <Input id="macId" type="text" placeholder="Enter macid" {...register("macId")} />
        {errors.macId && <p className="text-sm text-red-500">{String(errors.macId?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="transactionId" className="text-sm font-medium">transactionid</label>
        <Input id="transactionId" type="text" placeholder="Enter transactionid" {...register("transactionId")} />
        {errors.transactionId && <p className="text-sm text-red-500">{String(errors.transactionId?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountBallance" className="text-sm font-medium">TotalBalancecustomer</label>
        <Input id="accountBallance" type="text" placeholder="Enter totalbalancecustomer" {...register("accountBallance")} />
        {errors.accountBallance && <p className="text-sm text-red-500">{String(errors.accountBallance?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="ballanceBeforeDeposite" className="text-sm font-medium">fillbalancebeforedeosite</label>
        <Input id="ballanceBeforeDeposite" type="url" placeholder="Enter fillbalancebeforedeosite" {...register("ballanceBeforeDeposite")} />
        {errors.ballanceBeforeDeposite && <p className="text-sm text-red-500">{String(errors.ballanceBeforeDeposite?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="newTotalBallance" className="text-sm font-medium">newtotalballance</label>
        <Input id="newTotalBallance" type="text" placeholder="Enter newtotalballance" {...register("newTotalBallance")} />
        {errors.newTotalBallance && <p className="text-sm text-red-500">{String(errors.newTotalBallance?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="depositeBallance" className="text-sm font-medium">depositeballance</label>
        <Input id="depositeBallance" type="url" placeholder="Enter depositeballance" {...register("depositeBallance")} />
        {errors.depositeBallance && <p className="text-sm text-red-500">{String(errors.depositeBallance?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountBallance" className="text-sm font-medium">balancebeforedeposite</label>
        <Input id="accountBallance" type="url" placeholder="Enter balancebeforedeposite" {...register("accountBallance")} />
        {errors.accountBallance && <p className="text-sm text-red-500">{String(errors.accountBallance?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="depositeDate" className="text-sm font-medium">datecap</label>
        <Input id="depositeDate" type="url" placeholder="Enter datecap" {...register("depositeDate")} />
        {errors.depositeDate && <p className="text-sm text-red-500">{String(errors.depositeDate?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="accountNo" className="text-sm font-medium">Label1</label>
        <Input id="accountNo" type="text" placeholder="Enter label1" {...register("accountNo")} />
        {errors.accountNo && <p className="text-sm text-red-500">{String(errors.accountNo?.message ?? "")}</p>}
      </div>
      <Button type="submit">Save</Button>
    </form>
  );
}
