"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { howToUseSchema, type HowToUseInput } from "@/lib/validation/howToUse";

// How To Use — create/edit form, generated by RNC from the UIR.
export default function HowToUseForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<HowToUseInput>({ resolver: zodResolver(howToUseSchema) });

  async function onSubmit(values: HowToUseInput) {
    const res = await fetch("/api/how_to_uses", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/how_to_uses");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">How To Use</h1>
      <Button type="submit">Save</Button>
    </form>
  );
}
