"use client";
import useSWR from "swr";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Yt Bank Of India Management System Version10s — list view, generated by RNC from the UIR.
export default function YtBankOfIndiaManagementSystemVersion10sPage() {
  const { data, isLoading } = useSWR(`/api/yt_bank_of_india_management_system_version_1_0s?page=1&limit=20`, fetcher);
  const rows = data?.data ?? [];

  return (
    <div className="container mx-auto py-8">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold">Yt Bank Of India Management System Version10s</h1>
        <Button asChild><Link href="/yt_bank_of_india_management_system_version_1_0s/new">New Yt Bank Of India Management System Version 1 0</Link></Button>
      </div>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b text-left">
            <th className="py-2"></th>
          </tr>
        </thead>
        <tbody>
          {isLoading && (<tr><td className="py-4 text-muted-foreground">Loading…</td></tr>)}
          {rows.map((row: any) => (
            <tr key={row.id} className="border-b">
              <td className="py-2">
                <Button variant="ghost" size="sm" asChild>
                  <Link href={`/yt_bank_of_india_management_system_version_1_0s/${row.id}/edit`}>Edit</Link>
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
