"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { pickOrderNoDlgSchema, type PickOrderNoDlgInput } from "@/lib/validation/pickOrderNoDlg";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Pick Order No Dlg — edit view, generated by RNC from the UIR.
export default function PickOrderNoDlgEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/pick_order_no_dlgs/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<PickOrderNoDlgInput>({ resolver: zodResolver(pickOrderNoDlgSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: PickOrderNoDlgInput) {
    const res = await fetch(`/api/pick_order_no_dlgs/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/pick_order_no_dlgs");
  }

  async function onDelete() {
    const res = await fetch(`/api/pick_order_no_dlgs/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/pick_order_no_dlgs");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/pick_order_no_dlgs"><ArrowLeft className="h-4 w-4" /> Back to Pick Order No Dlgs</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Pick Order No Dlg</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="dblookupListBox1" className="text-sm font-medium">Dblookup List Box</label>
                <Controller
                  control={control}
                  name={"dblookupListBox1" as never}
                  render={({ field }) => (
                    <Select value={(field.value as string) ?? ""} onValueChange={field.onChange}>
                      <SelectTrigger id="dblookupListBox1"><SelectValue placeholder="Select…" /></SelectTrigger>
                      <SelectContent>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.dblookupListBox1 && <p className="text-sm text-destructive">{String(errors.dblookupListBox1?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
