"use client";
import useSWR from "swr";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Admin Details — list view, generated by RNC from the UIR.
export default function AdminDetailsPage() {
  const { data, isLoading } = useSWR(`/api/admin_details?page=1&limit=20`, fetcher);
  const rows = data?.data ?? [];

  return (
    <div className="container mx-auto py-8">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold">Admin Details</h1>
        <Button asChild><Link href="/admin_details/new">New Staff Profile</Link></Button>
      </div>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b text-left">
            <th className="py-2 pr-4">Label18</th>
            <th className="py-2 pr-4">Label4</th>
            <th className="py-2 pr-4">Label6</th>
            <th className="py-2 pr-4">Label8</th>
            <th className="py-2 pr-4">Label10</th>
            <th className="py-2 pr-4">Label12</th>
            <th className="py-2 pr-4">Label14</th>
            <th className="py-2 pr-4">Label17</th>
            <th className="py-2 pr-4">showimglink</th>
            <th className="py-2"></th>
          </tr>
        </thead>
        <tbody>
          {isLoading && (<tr><td className="py-4 text-muted-foreground">Loading…</td></tr>)}
          {rows.map((row: any) => (
            <tr key={row.id} className="border-b">
              <td className="py-2 pr-4">{String(row.doj ?? "")}</td>
              <td className="py-2 pr-4">{String(row.name ?? "")}</td>
              <td className="py-2 pr-4">{String(row.id ?? "")}</td>
              <td className="py-2 pr-4">{String(row.email ?? "")}</td>
              <td className="py-2 pr-4">{String(row.phoneno ?? "")}</td>
              <td className="py-2 pr-4">{String(row.address ?? "")}</td>
              <td className="py-2 pr-4">{String(row.pin ?? "")}</td>
              <td className="py-2 pr-4">{String(row.gender ?? "")}</td>
              <td className="py-2 pr-4">{String(row.image ?? "")}</td>
              <td className="py-2">
                <Button variant="ghost" size="sm" asChild>
                  <Link href={`/admin_details/${row.id}/edit`}>Edit</Link>
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
