"use client";
import { useEffect } from "react";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { withdrawSchema, type WithdrawInput } from "@/lib/validation/withdraw";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Withdraw Balance Yt Bank Of India — edit view, generated by RNC from the UIR.
export default function WithdrawEditForm() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const { data, isLoading } = useSWR(`/api/withdraws/${params.id}`, fetcher);
  const { register, handleSubmit, control, reset, formState: { errors, isSubmitting } } =
    useForm<WithdrawInput>({ resolver: zodResolver(withdrawSchema) });

  useEffect(() => { if (data) reset(data); }, [data, reset]);

  async function onSubmit(values: WithdrawInput) {
    const res = await fetch(`/api/withdraws/${params.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/withdraws");
  }

  async function onDelete() {
    const res = await fetch(`/api/withdraws/${params.id}`, { method: "DELETE" });
    if (res.ok) router.push("/withdraws");
  }

  return (
    <div className="container mx-auto max-w-2xl px-4 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/withdraws"><ArrowLeft className="h-4 w-4" /> Back to Withdraws</Link>
      </Button>
      {isLoading ? (
        <Card>
          <CardContent className="space-y-4 py-6">
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
            <Skeleton className="h-9 w-full" />
          </CardContent>
        </Card>
      ) : (
        <form onSubmit={handleSubmit(onSubmit)}>
          <Card>
            <CardHeader>
              <CardTitle>Edit Withdraw Balance Yt Bank Of India</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <label htmlFor="accountBallance" className="text-sm font-medium">Account Balance</label>
                <Input id="accountBallance" type="text" placeholder="Enter account balance" {...register("accountBallance")} />
                {errors.accountBallance && <p className="text-sm text-destructive">{String(errors.accountBallance?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="withdrawBalance" className="text-sm font-medium">Withdraw Balance</label>
                <Input id="withdrawBalance" type="text" placeholder="Enter withdraw balance" {...register("withdrawBalance")} />
                {errors.withdrawBalance && <p className="text-sm text-destructive">{String(errors.withdrawBalance?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="newTotalBalance" className="text-sm font-medium">New Total Balance</label>
                <Input id="newTotalBalance" type="text" placeholder="Enter new total balance" {...register("newTotalBalance")} />
                {errors.newTotalBalance && <p className="text-sm text-destructive">{String(errors.newTotalBalance?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="balanceBeforeWithdraw" className="text-sm font-medium">Balance Before Withdraw</label>
                <Input id="balanceBeforeWithdraw" type="text" placeholder="Enter balance before withdraw" {...register("balanceBeforeWithdraw")} />
                {errors.balanceBeforeWithdraw && <p className="text-sm text-destructive">{String(errors.balanceBeforeWithdraw?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="accountBallance" className="text-sm font-medium">Account Balance</label>
                <Input id="accountBallance" type="text" placeholder="Enter account balance" {...register("accountBallance")} />
                {errors.accountBallance && <p className="text-sm text-destructive">{String(errors.accountBallance?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="transactionId" className="text-sm font-medium">Transaction Id</label>
                <Input id="transactionId" type="text" placeholder="Enter transaction id" {...register("transactionId")} />
                {errors.transactionId && <p className="text-sm text-destructive">{String(errors.transactionId?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="macId" className="text-sm font-medium">Mac Id</label>
                <Input id="macId" type="text" placeholder="Enter mac id" {...register("macId")} />
                {errors.macId && <p className="text-sm text-destructive">{String(errors.macId?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="accountNo" className="text-sm font-medium">Account No</label>
                <Input id="accountNo" type="text" placeholder="Enter account no" {...register("accountNo")} />
                {errors.accountNo && <p className="text-sm text-destructive">{String(errors.accountNo?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="accountNo" className="text-sm font-medium">Account No</label>
                <Input id="accountNo" type="text" placeholder="Enter account no" {...register("accountNo")} />
                {errors.accountNo && <p className="text-sm text-destructive">{String(errors.accountNo?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="withdrawTime" className="text-sm font-medium">Withdraw Time</label>
                <Input id="withdrawTime" type="text" placeholder="Enter withdraw time" {...register("withdrawTime")} />
                {errors.withdrawTime && <p className="text-sm text-destructive">{String(errors.withdrawTime?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="withdrawDate" className="text-sm font-medium">Withdraw Date</label>
                <Input id="withdrawDate" type="text" placeholder="Enter withdraw date" {...register("withdrawDate")} />
                {errors.withdrawDate && <p className="text-sm text-destructive">{String(errors.withdrawDate?.message ?? "")}</p>}
              </div>
              <div className="space-y-1.5">
                <label htmlFor="accountNo" className="text-sm font-medium">Account No</label>
                <Input id="accountNo" type="text" placeholder="Enter account no" {...register("accountNo")} />
                {errors.accountNo && <p className="text-sm text-destructive">{String(errors.accountNo?.message ?? "")}</p>}
              </div>
            </CardContent>
            <CardFooter className="justify-between gap-2">
              <Button type="button" variant="outline" onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4" /> Delete
              </Button>
              <Button type="submit" disabled={isSubmitting}>Save changes</Button>
            </CardFooter>
          </Card>
        </form>
      )}
    </div>
  );
}
