"use client";
import useSWR from "swr";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Withdraw Transaction Histories — list view, generated by RNC from the UIR.
export default function WithdrawTransactionHistoriesPage() {
  const { data, isLoading } = useSWR(`/api/withdraw_transaction_histories?page=1&limit=20`, fetcher);
  const rows = data?.data ?? [];

  return (
    <div className="container mx-auto py-8">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold">Withdraw Transaction Histories</h1>
        <Button asChild><Link href="/withdraw_transaction_histories/new">New Withdraw Transaction History</Link></Button>
      </div>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b text-left">
            <th className="py-2"></th>
          </tr>
        </thead>
        <tbody>
          {isLoading && (<tr><td className="py-4 text-muted-foreground">Loading…</td></tr>)}
          {rows.map((row: any) => (
            <tr key={row.id} className="border-b">
              <td className="py-2">
                <Button variant="ghost" size="sm" asChild>
                  <Link href={`/withdraw_transaction_histories/${row.id}/edit`}>Edit</Link>
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
