"use client";
import { useState } from "react";
import useSWR from "swr";
import Link from "next/link";
import { Plus, Search, Pencil, Inbox } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { useEntityConfig, formatValue } from "@/lib/ui-settings";
import { ENTITY_COLS } from "@/lib/entity-columns";

const fetcher = (url: string) => fetch(url).then((r) => r.json());
const PAGE_SIZE = 20;
const ENTITY = "employees";

// Employees — list view, generated by RNC from the UIR.
export default function Page() {
  const [page, setPage] = useState(1);
  const [query, setQuery] = useState("");
  const { data, isLoading } = useSWR(`/api/employees?page=${page}&limit=${PAGE_SIZE}`, fetcher);
  const cols = useEntityConfig(ENTITY, ENTITY_COLS[ENTITY] ?? []);
  const visibleCols = cols.filter((c) => c.visible);

  const rows: any[] = data?.data ?? [];
  const total: number = data?.total ?? 0;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  const filtered = query
    ? rows.filter((row) =>
        Object.values(row).some((v) => String(v ?? "").toLowerCase().includes(query.toLowerCase())),
      )
    : rows;

  return (
    <div className="w-full px-6 py-8">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Employees</h1>
          <p className="text-sm text-muted-foreground">{total} record{total === 1 ? "" : "s"}</p>
        </div>
        <Button asChild>
          <Link href="/employees/new"><Plus className="h-4 w-4" /> New Employee</Link>
        </Button>
      </div>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between gap-4 space-y-0">
          <CardTitle className="text-base">All Employees</CardTitle>
          <div className="relative w-full max-w-xs">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="pl-8"
            />
          </div>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-2">
              <Skeleton className="h-10 w-full" />
              <Skeleton className="h-10 w-full" />
              <Skeleton className="h-10 w-full" />
            </div>
          ) : filtered.length === 0 ? (
            <div className="flex flex-col items-center justify-center gap-2 py-16 text-center">
              <Inbox className="h-10 w-10 text-muted-foreground" />
              <p className="font-medium">No Employees found</p>
              <p className="text-sm text-muted-foreground">
                {query ? "Try a different search." : "Create the first record to get started."}
              </p>
              {!query && (
                <Button asChild variant="outline" className="mt-2">
                  <Link href="/employees/new"><Plus className="h-4 w-4" /> New Employee</Link>
                </Button>
              )}
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  {visibleCols.map((c) => <TableHead key={c.key}>{c.label}</TableHead>)}
                  <TableHead className="w-0" />
                </TableRow>
              </TableHeader>
              <TableBody>
                {filtered.map((row) => (
                  <TableRow key={row.id}>
                    {visibleCols.map((c) => (
                      <TableCell key={c.key}>{formatValue(row[c.key], c.format)}</TableCell>
                    ))}
                    <TableCell className="text-right">
                      <Button variant="ghost" size="sm" asChild>
                        <Link href={`/employees/${row.id}/edit`}><Pencil className="h-4 w-4" /> Edit</Link>
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {totalPages > 1 && (
        <div className="mt-4 flex items-center justify-end gap-2">
          <span className="text-sm text-muted-foreground">Page {page} of {totalPages}</span>
          <Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>
            Previous
          </Button>
          <Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)}>
            Next
          </Button>
        </div>
      )}
    </div>
  );
}
