import { z } from "zod";

// Validation schema for AvisosUsuario — generated by RNC from the UIR.
export const avisosUsuarioSchema = z.object({
  id: z.coerce.number().int(),
  mensagem: z.string().min(1),
  perfil: z.string().nullish(),
  data: z.coerce.date(),
  itemIs: z.coerce.number().int().nullish(),
  validado: z.string().nullish(),
  ignorar: z.string().nullish(),
  lancado: z.string().nullish(),
  ignorarChefia: z.string().nullish(),
});

export type AvisosUsuarioInput = z.infer<typeof avisosUsuarioSchema>;
