import { z } from "zod";

// Validation schema for Dependente — generated by RNC from the UIR.
export const dependenteSchema = z.object({
  id: z.coerce.number().int(),
  nome: z.string().min(1),
  dataNascimento: z.coerce.date().nullish(),
  parentesco: z.string().nullish(),
  cpf: z.string().nullish(),
  sexo: z.string().nullish(),
  dadosBancarios: z.string().nullish(),
  documentos: z.string().nullish(),
  endereco: z.string().nullish(),
});

export type DependenteInput = z.infer<typeof dependenteSchema>;
