// Sidebar navigation — generated by RNC from the UIR.
// `icon` is a statically-imported Lucide component (no lucide-react/dynamic) so only
// the icons actually used are bundled — keeps dev compile fast.
import { Briefcase, Building2, Table, Users, type LucideIcon } from 'lucide-react';

export interface NavItem { label: string; href: string; icon: LucideIcon }

export const appName = "Bombeiros ES";

export const navItems: NavItem[] = [
  { label: "Funcionarios", href: "/funcionarios", icon: Briefcase },
  { label: "Dependentes", href: "/dependentes", icon: Users },
  { label: "Lotacaos", href: "/lotacaos", icon: Building2 },
  { label: "Avisos Usuarios", href: "/avisos_usuarios", icon: Users },
];
