"use client";
import useSWR from "swr";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { ComboboxCreate } from "@/components/ui/combobox-create";
import { partsSchema, type PartsInput } from "@/lib/validation/parts";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

// Lookup field → options fetched live from the referenced entity's API.
function RelationSelect({ route, optionLabel, value, onChange }: {
  route: string; optionLabel: string; value: string; onChange: (v: string) => void;
}) {
  const { data } = useSWR(`/api/${route}?page=1&limit=100`, fetcher);
  const rows: any[] = data?.data ?? [];
  function label(row: any): string {
    if (row[optionLabel] != null && row[optionLabel] !== "") return String(row[optionLabel]);
    for (const [k, v] of Object.entries(row)) {
      if (k === "id" || k.endsWith("Id") || k.endsWith("_id")) continue;
      if (typeof v === "string" && v !== "") return v;
    }
    return String(row.id);
  }
  return (
    <Select value={value ?? ""} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Select…" /></SelectTrigger>
      <SelectContent>
        {rows.map((row) => (
          <SelectItem key={row.id} value={String(row.id)}>{label(row)}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// Ed Parts — create/edit form, generated by RNC from the UIR.
export default function PartsForm() {
  const router = useRouter();
  const { register, handleSubmit, control, formState: { errors, isSubmitting } } =
    useForm<PartsInput>({ resolver: zodResolver(partsSchema) });

  async function onSubmit(values: PartsInput) {
    const res = await fetch("/api/parts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/parts");
  }

  return (
    <div className="w-full px-6 py-8">
      <Button variant="ghost" size="sm" asChild className="mb-4">
        <Link href="/parts"><ArrowLeft className="h-4 w-4" /> Back to Parts</Link>
      </Button>
      <form onSubmit={handleSubmit(onSubmit)}>
        <Card>
          <CardHeader>
            <CardTitle>Ed Parts</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <label htmlFor="onHand" className="text-sm font-medium">On Hand</label>
              <Input id="onHand" type="text" placeholder="Enter on hand" {...register("onHand")} />
              {errors.onHand && <p className="text-sm text-destructive">{String(errors.onHand?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="onOrder" className="text-sm font-medium">On Order</label>
              <Input id="onOrder" type="text" placeholder="Enter on order" {...register("onOrder")} />
              {errors.onOrder && <p className="text-sm text-destructive">{String(errors.onOrder?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="cost" className="text-sm font-medium">Cost</label>
              <div className="relative">
                <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                <Input id="cost" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("cost", { valueAsNumber: true })} />
              </div>
              {errors.cost && <p className="text-sm text-destructive">{String(errors.cost?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="listPrice" className="text-sm font-medium">List Price</label>
              <div className="relative">
                <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                <Input id="listPrice" type="number" step="0.01" min="0" placeholder="0.00" className="pl-7" {...register("listPrice", { valueAsNumber: true })} />
              </div>
              {errors.listPrice && <p className="text-sm text-destructive">{String(errors.listPrice?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="partNo" className="text-sm font-medium">Part No</label>
              <Input id="partNo" type="text" placeholder="Enter part no" {...register("partNo")} />
              {errors.partNo && <p className="text-sm text-destructive">{String(errors.partNo?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="vendorNo" className="text-sm font-medium">Vendor No</label>
              <Controller
                control={control}
                name={"vendorNo" as never}
                render={({ field }) => (
                  <ComboboxCreate
                    name="vendorNo"
                    route="vendors"
                    optionLabel="id"
                    createFields={[{"name":"name","label":"Vendors Name","inputType":"text","required":true}]}
                    value={(field.value as string) ?? ""}
                    onChange={field.onChange}
                  />
                )}
              />
              {errors.vendorNo && <p className="text-sm text-destructive">{String(errors.vendorNo?.message ?? "")}</p>}
            </div>
            <div className="space-y-1.5">
              <label htmlFor="description" className="text-sm font-medium">Description</label>
              <Textarea id="description" placeholder="Enter description" {...register("description")} />
              {errors.description && <p className="text-sm text-destructive">{String(errors.description?.message ?? "")}</p>}
            </div>
          </CardContent>
          <CardFooter className="justify-end gap-2">
            <Button type="button" variant="outline" asChild>
              <Link href="/parts">Cancel</Link>
            </Button>
            <Button type="submit" disabled={isSubmitting}>Save</Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  );
}
