"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { ytBankOfIndiaManagementSystemVersion10Schema, type YtBankOfIndiaManagementSystemVersion10Input } from "@/lib/validation/ytBankOfIndiaManagementSystemVersion10";

// Yt Bank Of India Management System Version 1 0 — create/edit form, generated by RNC from the UIR.
export default function YtBankOfIndiaManagementSystemVersion10Form() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<YtBankOfIndiaManagementSystemVersion10Input>({ resolver: zodResolver(ytBankOfIndiaManagementSystemVersion10Schema) });

  async function onSubmit(values: YtBankOfIndiaManagementSystemVersion10Input) {
    const res = await fetch("/api/yt_bank_of_india_management_system_version_1_0s", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/yt_bank_of_india_management_system_version_1_0s");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Yt Bank Of India Management System Version 1 0</h1>
      <Button type="submit">Save</Button>
    </form>
  );
}
