"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { adminDetailsSchema, type AdminDetailsInput } from "@/lib/validation/adminDetails";

// Staff Profile — create/edit form, generated by RNC from the UIR.
export default function AdminDetailsForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<AdminDetailsInput>({ resolver: zodResolver(adminDetailsSchema) });

  async function onSubmit(values: AdminDetailsInput) {
    const res = await fetch("/api/admin_details", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/admin_details");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Staff Profile</h1>
      <div className="space-y-1">
        <label htmlFor="doj" className="text-sm font-medium">Label18</label>
        <Input id="doj" type="text" placeholder="Enter label18" {...register("doj")} />
        {errors.doj && <p className="text-sm text-red-500">{String(errors.doj?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="name" className="text-sm font-medium">Label4</label>
        <Input id="name" type="text" placeholder="Enter label4" {...register("name")} />
        {errors.name && <p className="text-sm text-red-500">{String(errors.name?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="id" className="text-sm font-medium">Label6</label>
        <Input id="id" type="text" placeholder="Enter label6" {...register("id")} />
        {errors.id && <p className="text-sm text-red-500">{String(errors.id?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="email" className="text-sm font-medium">Label8</label>
        <Input id="email" type="email" placeholder="Enter label8" {...register("email")} />
        {errors.email && <p className="text-sm text-red-500">{String(errors.email?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="phoneno" className="text-sm font-medium">Label10</label>
        <Input id="phoneno" type="tel" placeholder="Enter label10" {...register("phoneno")} />
        {errors.phoneno && <p className="text-sm text-red-500">{String(errors.phoneno?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="address" className="text-sm font-medium">Label12</label>
        <Input id="address" type="text" placeholder="Enter label12" {...register("address")} />
        {errors.address && <p className="text-sm text-red-500">{String(errors.address?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="pin" className="text-sm font-medium">Label14</label>
        <Input id="pin" type="text" placeholder="Enter label14" {...register("pin")} />
        {errors.pin && <p className="text-sm text-red-500">{String(errors.pin?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="gender" className="text-sm font-medium">Label17</label>
        <Input id="gender" type="text" placeholder="Enter label17" {...register("gender")} />
        {errors.gender && <p className="text-sm text-red-500">{String(errors.gender?.message ?? "")}</p>}
      </div>
      <div className="space-y-1">
        <label htmlFor="image" className="text-sm font-medium">showimglink</label>
        <Input id="image" type="text" placeholder="Enter showimglink" {...register("image")} />
        {errors.image && <p className="text-sm text-red-500">{String(errors.image?.message ?? "")}</p>}
      </div>
      <Button type="submit">Save</Button>
    </form>
  );
}
