"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { forgetPasswordBankStaffSchema, type ForgetPasswordBankStaffInput } from "@/lib/validation/forgetPasswordBankStaff";

// Forget Password Bank Staff — create/edit form, generated by RNC from the UIR.
export default function ForgetPasswordBankStaffForm() {
  const router = useRouter();
  const { register, handleSubmit, setValue, formState: { errors } } =
    useForm<ForgetPasswordBankStaffInput>({ resolver: zodResolver(forgetPasswordBankStaffSchema) });

  async function onSubmit(values: ForgetPasswordBankStaffInput) {
    const res = await fetch("/api/forget_password_bank_staffs", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(values),
    });
    if (res.ok) router.push("/forget_password_bank_staffs");
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="container mx-auto max-w-xl space-y-4 py-8">
      <h1 className="text-2xl font-bold">Forget Password Bank Staff</h1>
      <Button type="submit">Save</Button>
    </form>
  );
}
